<a href="https://colab.research.google.com/github/mfernandezzz/Pruebas_Tecnicas/blob/main/pruebaTecnicaNetflix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**¿Cual es la pelicula que mas dura en Netflix?**

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv('/content/netflix_titles.csv')
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [ ]:
df.shape

(8807, 12)

In [ ]:
df['type'].value_counts()

type
Movie      6131
TV Show    2676
Name: count, dtype: int64

Nuevo DataFrame solo con las peliculas

In [ ]:
df_movies = df[df['type'] == 'Movie']
df_movies.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90,Documentaries,"As her father nears the end of his life, filmm..."
6,s7,Movie,My Little Pony: A New Generation,"Robert Cullen, José Luis Ucha","Vanessa Hudgens, Kimiko Glenn, James Marsden, ...",NaN,"September 24, 2021",2021,PG,91,Children & Family Movies,Equestria's divided. But a bright-eyed hero be...
7,s8,Movie,Sankofa,Haile Gerima,"Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra D...","United States, Ghana, Burkina Faso, United Kin...","September 24, 2021",1993,TV-MA,125,"Dramas, Independent Movies, International Movies","On a photo shoot in Ghana, an American model s..."
9,s10,Movie,The Starling,Theodore Melfi,"Melissa McCarthy, Chris O'Dowd, Kevin Kline, T...",United States,"September 24, 2021",2021,PG-13,104,"Comedies, Dramas",A woman adjusting to life after a loss contend...
12,s13,Movie,Je Suis Karl,Christian Schwochow,"Luna Wedler, Jannis Niewöhner, Milan Peschel, ...","Germany, Czech Republic","September 23, 2021",2021,TV-MA,127,"Dramas, International Movies",After most of her family is murdered in a terr...

In [ ]:
#mask = df['type'] == 'Movie'
#df_movies = df[mask]
#df_movies.head()

In [ ]:
df_movies.dtypes

show_id         object
type            object
title           object
director        object
cast            object
country         object
date_added      object
release_year     int64
rating          object
duration        object
listed_in       object
description     object
dtype: object

Existencia de valores nulos en la columna 'duration'

In [ ]:
null_values = df['duration'].isna().sum()
null_values

np.int64(3)

Se visualiza las filas que contienen valor nulo en la columna 'duration'

In [ ]:
mask_null = df_movies['duration'].isna()
df_movies[mask_null]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
5541,s5542,Movie,Louis C.K. 2017,Louis C.K.,Louis C.K.,United States,"April 4, 2017",2017,74 min,NaN,Movies,"Louis C.K. muses on religion, eternal love, gi..."
5794,s5795,Movie,Louis C.K.: Hilarious,Louis C.K.,Louis C.K.,United States,"September 16, 2016",2010,84 min,NaN,Movies,Emmy-winning comedy writer Louis C.K. brings h...
5813,s5814,Movie,Louis C.K.: Live at the Comedy Store,Louis C.K.,Louis C.K.,United States,"August 15, 2016",2015,66 min,NaN,Movies,The comic puts his trademark hilarious/thought...

In [ ]:
# mask = df_movies['duration'].isna()
# df_movies.loc[mask, 'duration'] = df_movies.loc[mask, 'duration'].fillna('0')

Lista que almacena las duraciones de las peliculas

In [ ]:
duracion_peliculas = df_movies['duration'].to_list()
len(duracion_peliculas)

6131

Funcion para iterar sobre la lista, transformar cada string a numero decimal y devolver el valor numerico mas alto

In [ ]:
def maxima_duracion(lista):
  duration = [float(d) for d in lista]
  return max(duration)

f'La duracion maxima de una pelicula en el DataFrame es de {maxima_duracion(duracion_peliculas)} minutos.'

'La duracion maxima de una pelicula en el DataFrame es de 273.0 minutos.'

Obtener los datos de la pelicula cuya duracion es la obtenida previamente

In [ ]:
mask = df_movies['duration'] == '273'
longest_movie = df_movies[mask]
longest_movie[['type', 'title', 'date_added', 'release_year', 'rating', 'duration', 'listed_in', 'description']]

,type,title,date_added,release_year,rating,duration,listed_in,description
717,Movie,Headspace: Unwind Your Mind,"June 15, 2021",2021,TV-G,273,Documentaries,"Do you want to relax, meditate or sleep deeply..."

Otra solucion

In [ ]:
df_moviess = df[df['type'] == 'Movie'][['title', 'duration']]
df_moviess.head()

                               title duration
0               Dick Johnson Is Dead       90
6   My Little Pony: A New Generation       91
7                            Sankofa      125
9                       The Starling      104
12                      Je Suis Karl      127

In [ ]:
id_longest_movie = df_moviess['duration'].fillna('0')
id_longest_movie.astype(int).idxmax()

np.int64(717)

In [ ]:
longest_movie = df.loc[id_longest_movie.astype(int).idxmax()]
longest_movie[['type', 'title', 'date_added', 'release_year', 'rating', 'duration', 'listed_in', 'description']]

type                                                        Movie
title                                 Headspace: Unwind Your Mind
date_added                                          June 15, 2021
release_year                                                 2021
rating                                                       TV-G
duration                                                      273
listed_in                                           Documentaries
description     Do you want to relax, meditate or sleep deeply...
Name: 717, dtype: object

**¿En que año se subieron (date_added) mas peliculas a Netflix?**

In [ ]:
df_movies.columns

Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in', 'description'],
      dtype='object')

In [ ]:
df_movies.dtypes

show_id         object
type            object
title           object
director        object
cast            object
country         object
date_added      object
release_year     int64
rating          object
duration        object
listed_in       object
description     object
dtype: object

In [ ]:
df_movies['date_added'].value_counts()

date_added
January 1, 2020      97
November 1, 2019     75
March 1, 2018        72
December 31, 2019    67
October 1, 2018      64
                     ..
June 23, 2019         1
December 23, 2018     1
October 26, 2019      1
April 21, 2019        1
May 26, 2016          1
Name: count, Length: 1533, dtype: int64

Se comprueba la existencia de valores nulos

In [ ]:
df_movies['date_added'].isna().sum()

np.int64(0)

Buscar la cantidad de peliculas que se subieron a Netflix por año

In [ ]:
mask2021 = df_movies['date_added'].str.contains('2021')
df_2021 = df_movies[mask2021]
df_2021.shape[0]

993

In [ ]:
mask2020 = df_movies['date_added'].str.contains('2020')
df_2020 = df_movies[mask2020]
df_2020.shape[0]

1284

2019 es el año con mas cantidad de peliculas subidas a la plataforma Netflix

In [ ]:
mask2019 = df_movies['date_added'].str.contains('2019')
df_2019 = df_movies[mask2019]
df_2019.shape[0]

1424

In [ ]:
mask2018 = df_movies['date_added'].str.contains('2018')
df_2018 = df_movies[mask2018]
df_2018.shape[0]

1237

In [ ]:
mask2017 = df_movies['date_added'].str.contains('2017')
df_2017 = df_movies[mask2017]
df_2017.shape[0]

839

In [ ]:
mask2016 = df_movies['date_added'].str.contains('2016')
df_2016 = df_movies[mask2016]
df_2016.shape[0]

253

In [ ]:
mask2015 = df_movies['date_added'].str.contains('2015')
df_2015 = df_movies[mask2015]
df_2015.shape[0]

56

In [ ]:
mask2014 = df_movies['date_added'].str.contains('2014')
df_2014 = df_movies[mask2014]
df_2014.shape[0]

19

In [ ]:
mask2013 = df_movies['date_added'].str.contains('2013')
df_2013 = df_movies[mask2013]
df_2013.shape[0]

6

In [ ]:
mask2012 = df_movies['date_added'].str.contains('2012')
df_2012 = df_movies[mask2012]
df_2012.shape[0]

3

In [ ]:
mask2011 = df_movies['date_added'].str.contains('2011')
df_2011 = df_movies[mask2011]
df_2011.shape[0]

13

In [ ]:
mask2010 = df_movies['date_added'].str.contains('2010')
df_2010 = df_movies[mask2010]
df_2010.shape[0]

1

In [ ]:
mask2009 = df_movies['date_added'].str.contains('2009')
df_2009 = df_movies[mask2009]
df_2009.shape[0]

2

In [ ]:
mask2008 = df_movies['date_added'].str.contains('2008')
df_2008 = df_movies[mask2008]
df_2008.shape[0]

1

**¿En que año se estrenaron (release_year) mas peliculas?**

In [ ]:
conteo_peliculas = df_movies['release_year'].value_counts().head()
conteo_peliculas

release_year
2017    767
2018    767
2016    658
2019    633
2020    517
Name: count, dtype: int64

In [ ]:
conteo_peliculas.idxmax()

np.int64(2017)

In [ ]:
conteo_peliculas.max()

767

In [ ]:
f'El año en el que mas se estrenaron peliculas fue {conteo_peliculas.idxmax()} y la cantidad de peliculas estrenadas ese año fue {conteo_peliculas.max()}'

'El año en el que mas se estrenaron peliculas fue 2017 y la cantidad de peliculas estrenadas ese año fue 767'

In [ ]:
year_percentage_movies = pd.DataFrame(df_movies['release_year'].value_counts())
year_percentage_movies.rename(columns={'count': 'films'}, inplace=True)
year_percentage_movies['%'] = round(year_percentage_movies['films'] / year_percentage_movies['films'].sum() * 100, 2)
year_percentage_movies.head()

              films      %
release_year
2017            767  12.51
2018            767  12.51
2016            658  10.73
2019            633  10.32
2020            517   8.43

**¿Que pais produce mas series de Netflix?**

Filtrar por TV Show

In [ ]:
mask = df['type'] == 'TV Show'
df_series = df[mask]
df_series.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
5,s6,TV Show,Midnight Mass,Mike Flanagan,"Kate Siegel, Zach Gilford, Hamish Linklater, H...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"TV Dramas, TV Horror, TV Mysteries",The arrival of a charismatic young priest brin...

In [ ]:
df_series.shape[0]

2676

Se verifica la existencia de valores nulos en la columna 'country'

In [ ]:
df_series['country'].isna().sum()

np.int64(391)

Calcular el porcentaje de valores nulos en la columna 'country' con respecto a la totalidad de las columnas

In [ ]:
porcentaje_nulos = round(df_series['country'].isna().sum() / df_series.shape[0] * 100, 2)
f'El porcentaje de valores nulos en la columna Country para las Series es {porcentaje_nulos}%'

'El porcentaje de valores nulos en la columna Country para las Series es 14.61%'

Sustituir los valores nulos con el string 'No especificado'

In [ ]:
df_series['country'] = df_series['country'].fillna('No especificado')
df_series.head()

/tmp/ipykernel_3001/218567655.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_series['country'] = df_series['country'].fillna('No especificado')

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",No especificado,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,No especificado,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
5,s6,TV Show,Midnight Mass,Mike Flanagan,"Kate Siegel, Zach Gilford, Hamish Linklater, H...",No especificado,"September 24, 2021",2021,TV-MA,1 Season,"TV Dramas, TV Horror, TV Mysteries",The arrival of a charismatic young priest brin...

In [ ]:
f'El pais que produce mas Series para Netflix es: {df_series['country'].value_counts().idxmax()}'

'El pais que produce mas Series para Netflix es: United States'

In [ ]:
series_country_percentage = pd.DataFrame(df_series['country'].value_counts())
series_country_percentage.rename(columns={'count': 'Series'}, inplace=True)
series_country_percentage['%'] = round(series_country_percentage['Series'] / series_country_percentage['Series'].sum() * 100, 2)
series_country_percentage.head(1)

               Series     %
country
United States     760  28.4

**¿Cual es la duracion media de las peliculas por decada en Netflix?**

In [ ]:
df_movies.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90,Documentaries,"As her father nears the end of his life, filmm..."
6,s7,Movie,My Little Pony: A New Generation,"Robert Cullen, José Luis Ucha","Vanessa Hudgens, Kimiko Glenn, James Marsden, ...",NaN,"September 24, 2021",2021,PG,91,Children & Family Movies,Equestria's divided. But a bright-eyed hero be...
7,s8,Movie,Sankofa,Haile Gerima,"Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra D...","United States, Ghana, Burkina Faso, United Kin...","September 24, 2021",1993,TV-MA,125,"Dramas, Independent Movies, International Movies","On a photo shoot in Ghana, an American model s..."
9,s10,Movie,The Starling,Theodore Melfi,"Melissa McCarthy, Chris O'Dowd, Kevin Kline, T...",United States,"September 24, 2021",2021,PG-13,104,"Comedies, Dramas",A woman adjusting to life after a loss contend...
12,s13,Movie,Je Suis Karl,Christian Schwochow,"Luna Wedler, Jannis Niewöhner, Milan Peschel, ...","Germany, Czech Republic","September 23, 2021",2021,TV-MA,127,"Dramas, International Movies",After most of her family is murdered in a terr...

In [ ]:
df_movies.dtypes

show_id         object
type            object
title           object
director        object
cast            object
country         object
date_added      object
release_year     int64
rating          object
duration        object
listed_in       object
description     object
dtype: object

In [ ]:
df_movies['duration'] = df_movies['duration'].astype(float)
df_movies.head()

/tmp/ipykernel_3001/777645573.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_movies['duration'] = df_movies['duration'].astype(float)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90.0,Documentaries,"As her father nears the end of his life, filmm..."
6,s7,Movie,My Little Pony: A New Generation,"Robert Cullen, José Luis Ucha","Vanessa Hudgens, Kimiko Glenn, James Marsden, ...",NaN,"September 24, 2021",2021,PG,91.0,Children & Family Movies,Equestria's divided. But a bright-eyed hero be...
7,s8,Movie,Sankofa,Haile Gerima,"Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra D...","United States, Ghana, Burkina Faso, United Kin...","September 24, 2021",1993,TV-MA,125.0,"Dramas, Independent Movies, International Movies","On a photo shoot in Ghana, an American model s..."
9,s10,Movie,The Starling,Theodore Melfi,"Melissa McCarthy, Chris O'Dowd, Kevin Kline, T...",United States,"September 24, 2021",2021,PG-13,104.0,"Comedies, Dramas",A woman adjusting to life after a loss contend...
12,s13,Movie,Je Suis Karl,Christian Schwochow,"Luna Wedler, Jannis Niewöhner, Milan Peschel, ...","Germany, Czech Republic","September 23, 2021",2021,TV-MA,127.0,"Dramas, International Movies",After most of her family is murdered in a terr...

In [ ]:
df_movies.dtypes

show_id          object
type             object
title            object
director         object
cast             object
country          object
date_added       object
release_year      int64
rating           object
duration        float64
listed_in        object
description      object
dtype: object

Nueva columna con el valor de la decada correspondiente a cada año

In [ ]:
df_movies['decade'] = (df_movies['release_year'] // 10) * 10 # // division entera
df_movies.head()

/tmp/ipykernel_3001/3081884122.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_movies['decade'] = (df_movies['release_year'] // 10) * 10 # // division entera

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,decade
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90.0,Documentaries,"As her father nears the end of his life, filmm...",2020
6,s7,Movie,My Little Pony: A New Generation,"Robert Cullen, José Luis Ucha","Vanessa Hudgens, Kimiko Glenn, James Marsden, ...",NaN,"September 24, 2021",2021,PG,91.0,Children & Family Movies,Equestria's divided. But a bright-eyed hero be...,2020
7,s8,Movie,Sankofa,Haile Gerima,"Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra D...","United States, Ghana, Burkina Faso, United Kin...","September 24, 2021",1993,TV-MA,125.0,"Dramas, Independent Movies, International Movies","On a photo shoot in Ghana, an American model s...",1990
9,s10,Movie,The Starling,Theodore Melfi,"Melissa McCarthy, Chris O'Dowd, Kevin Kline, T...",United States,"September 24, 2021",2021,PG-13,104.0,"Comedies, Dramas",A woman adjusting to life after a loss contend...,2020
12,s13,Movie,Je Suis Karl,Christian Schwochow,"Luna Wedler, Jannis Niewöhner, Milan Peschel, ...","Germany, Czech Republic","September 23, 2021",2021,TV-MA,127.0,"Dramas, International Movies",After most of her family is murdered in a terr...,2020

Agrupar por decada y duracion promedio de peliculas por decada

In [ ]:
duration = round(df_movies.groupby('decade')['duration'].mean(), 2) # .idxmax()
duration

decade
1940     51.38
1950    107.09
1960    147.61
1970    119.24
1980    116.23
1990    113.84
2000    112.11
2010     96.87
2020     93.64
Name: duration, dtype: float64