<a href="https://colab.research.google.com/github/mfernandezzz/Pruebas_Tecnicas/blob/main/pruebaTecnicaGlassdoorJobs.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**¿Cuanto gana en promedio un Data Enginner?**

In [245]:
import pandas as pd
import numpy as np

In [246]:
df = pd.read_csv('/content/glassdoor_jobs_clean.csv')
df.head()

,Unnamed: 0.1,Unnamed: 0,Job Title,Salary Estimate,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors
0,0,0,Data Scientist,$53K-$91K (Glassdoor est.),3.8,Tecolote Research\n3.8,"Albuquerque, NM","Goleta, CA",501 to 1000 employees,1973,Company - Private,Aerospace & Defense,Aerospace & Defense,$50 to $100 million (USD),-1
1,1,1,Healthcare Data Scientist,$63K-$112K (Glassdoor est.),3.4,University of Maryland Medical System\n3.4,"Linthicum, MD","Baltimore, MD",10000+ employees,1984,Other Organization,Health Care Services & Hospitals,Health Care,$2 to $5 billion (USD),-1
2,2,2,Data Scientist,$80K-$90K (Glassdoor est.),4.8,KnowBe4\n4.8,"Clearwater, FL","Clearwater, FL",501 to 1000 employees,2010,Company - Private,Security Services,Business Services,$100 to $500 million (USD),-1
3,3,3,Data Scientist,$56K-$97K (Glassdoor est.),3.8,PNNL\n3.8,"Richland, WA","Richland, WA",1001 to 5000 employees,1965,Government,Energy,"Oil, Gas, Energy & Utilities",$500 million to $1 billion (USD),"Oak Ridge National Laboratory, National Renewa..."
4,4,4,Data Scientist,$86K-$143K (Glassdoor est.),2.9,Affinity Solutions\n2.9,"New York, NY","New York, NY",51 to 200 employees,1998,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable,"Commerce Signals, Cardlytics, Yodlee"

In [247]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 956 entries, 0 to 955
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0.1       956 non-null    int64
 1   Unnamed: 0         956 non-null    int64
 2   Job Title          956 non-null    object
 3   Salary Estimate    956 non-null    object
 4   Rating             956 non-null    float64
 5   Company Name       956 non-null    object
 6   Location           956 non-null    object
 7   Headquarters       956 non-null    object
 8   Size               956 non-null    object
 9   Founded            956 non-null    int64
 10  Type of ownership  956 non-null    object
 11  Industry           956 non-null    object
 12  Sector             956 non-null    object
 13  Revenue            956 non-null    object
 14  Competitors        956 non-null    object
dtypes: float64(1), int64(3), object(11)
memory usage: 112.2+ KB

In [248]:
#cantidad de registros correspondientes a cada profesion
df['Job Title'].value_counts()

Job Title
Data Scientist                                                       178
Data Engineer                                                         68
Senior Data Scientist                                                 42
Data Analyst                                                          18
Senior Data Engineer                                                  17
                                                                    ...
Jr. Data Scientist                                                     1
Data Architect / Data Modeler                                          1
Data Scientists                                                        1
Associate Scientist / Sr. Associate Scientist, Antibody Discovery      1
Machine Learning Engineer (NLP)                                        1
Name: count, Length: 328, dtype: int64

In [249]:
#se filtran las filas con los datos correspondientes a la profesion Data Enginner
#se filtran los resultados donde el valor para la columna Salary Estimate sea -1
mask = (df['Job Title'] == 'Data Engineer') & (df['Salary Estimate'] != '-1')
df_data_engineer = df[mask]
df_data_engineer.head(10)

,Unnamed: 0.1,Unnamed: 0,Job Title,Salary Estimate,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors
40,40,40,Data Engineer,$74K-$138K (Glassdoor est.),3.5,Lancer Insurance\n3.5,"Long Beach, NY","Long Beach, NY",201 to 500 employees,1985,Company - Private,Insurance Carriers,Insurance,$100 to $500 million (USD),-1
43,43,43,Data Engineer,$68K-$129K (Glassdoor est.),3.6,Persivia\n3.6,"Marlborough, MA","Lowell, MA",1 to 50 employees,-1,Company - Private,-1,-1,Less than $1 million (USD),-1
92,92,92,Data Engineer,$60K-$114K (Glassdoor est.),4.0,Excella Consulting\n4.0,"Arlington, VA","Arlington, VA",201 to 500 employees,2002,Company - Private,Consulting,Business Services,$50 to $100 million (USD),-1
118,118,118,Data Engineer,$68K-$123K (Glassdoor est.),3.9,CapTech\n3.9,"Charlotte, NC","Richmond, VA",1001 to 5000 employees,1997,Company - Private,IT Services,Information Technology,$100 to $500 million (USD),"Accenture, North Highland, Deloitte"
125,125,125,Data Engineer,$54K-$102K (Glassdoor est.),3.4,Sapphire Digital\n3.4,"Lyndhurst, NJ","Lyndhurst, NJ",201 to 500 employees,2019,Company - Private,Internet,Information Technology,Unknown / Non-Applicable,"Zocdoc, Healthgrades"
129,129,129,Data Engineer,$76K-$140K (Glassdoor est.),4.0,Autodesk\n4.0,"San Francisco, CA","San Rafael, CA",5001 to 10000 employees,1982,Company - Public,Computer Hardware & Software,Information Technology,$2 to $5 billion (USD),-1
132,132,132,Data Engineer,$65K-$125K (Glassdoor est.),4.7,Object Partners\n4.7,"Minneapolis, MN","Minneapolis, MN",51 to 200 employees,1996,Company - Private,Consulting,Business Services,$25 to $50 million (USD),"Solution Design Group, Intertech (Minnesota)"
140,140,140,Data Engineer,$85K-$159K (Glassdoor est.),4.0,Upside Business Travel\n4.0,"Washington, DC","Washington, DC",51 to 200 employees,2015,Company - Private,Internet,Information Technology,Unknown / Non-Applicable,-1
141,141,141,Data Engineer,$80K-$105K(Employer est.),4.3,Equity Residential\n4.3,"Chicago, IL","Chicago, IL",1001 to 5000 employees,1993,Company - Public,Real Estate,Real Estate,$2 to $5 billion (USD),"UDR, AvalonBay Communities, Essex Property Trust"
161,161,161,Data Engineer,Employer Provided Salary:$120K-$145K,5.0,Gridiron IT\n5.0,"Tampa, FL","Reston, VA",51 to 200 employees,2017,Company - Private,IT Services,Information Technology,Unknown / Non-Applicable,-1

In [250]:
#se crea una Serie solo con los datos de la columna Salary Estimate
salaries = pd.Series(df_data_engineer['Salary Estimate'])
salaries

40              $74K-$138K (Glassdoor est.)
43              $68K-$129K (Glassdoor est.)
92              $60K-$114K (Glassdoor est.)
118             $68K-$123K (Glassdoor est.)
125             $54K-$102K (Glassdoor est.)
129             $76K-$140K (Glassdoor est.)
132             $65K-$125K (Glassdoor est.)
140             $85K-$159K (Glassdoor est.)
141               $80K-$105K(Employer est.)
161    Employer Provided Salary:$120K-$145K
162             $80K-$120K (Glassdoor est.)
170             $60K-$114K (Glassdoor est.)
179             $59K-$110K (Glassdoor est.)
202              $48K-$95K (Glassdoor est.)
226              $48K-$93K (Glassdoor est.)
262             $59K-$110K (Glassdoor est.)
290             $62K-$114K (Glassdoor est.)
319              $48K-$95K (Glassdoor est.)
332             $70K-$132K (Glassdoor est.)
357              $52K-$99K (Glassdoor est.)
371             $67K-$117K (Glassdoor est.)
386              $48K-$93K (Glassdoor est.)
388             $65K-$119K (Glassdoor est.)
399             $75K-$143K (Glassdoor est.)
421             $65K-$124K (Glassdoor est.)
430              $43K-$86K (Glassdoor est.)
447             $74K-$124K (Glassdoor est.)
450             $76K-$142K (Glassdoor est.)
493             $61K-$109K (Glassdoor est.)
543             $65K-$119K (Glassdoor est.)
560             $63K-$120K (Glassdoor est.)
568             $75K-$143K (Glassdoor est.)
591             $76K-$145K (Glassdoor est.)
617             $65K-$124K (Glassdoor est.)
631             $55K-$105K (Glassdoor est.)
635              $57K-$80K (Glassdoor est.)
640              $43K-$86K (Glassdoor est.)
655             $79K-$147K (Glassdoor est.)
670             $74K-$124K (Glassdoor est.)
673             $76K-$142K (Glassdoor est.)
743             $61K-$109K (Glassdoor est.)
744              $42K-$79K (Glassdoor est.)
758             $74K-$137K (Glassdoor est.)
759             $57K-$109K (Glassdoor est.)
784             $65K-$126K (Glassdoor est.)
803             $58K-$104K (Glassdoor est.)
836             $65K-$124K (Glassdoor est.)
853             $55K-$105K (Glassdoor est.)
857              $57K-$80K (Glassdoor est.)
883             $79K-$147K (Glassdoor est.)
907             $74K-$124K (Glassdoor est.)
911             $76K-$142K (Glassdoor est.)
948             $62K-$113K (Glassdoor est.)
Name: Salary Estimate, dtype: object

Los datos almcenados en la columna 'Salary Estimate' son strings, los cuales representan un rango salarial. Por consiguiente, se debe modificar dichos strings para que el dato almacenado en la Serie sea lo mas parecido a un rango numerico.

In [251]:
salaries = salaries.str.replace('(Glassdoor est.)', '')
salaries = salaries.str.replace('K', '')
salaries = salaries.str.replace('$', '')
salaries = salaries.str.replace('Employer Provided Salary:', '')
salaries = salaries.str.replace('-', ',')
salaries = salaries.str.replace('(Employer est.)', '')
salaries = salaries.str.replace(' ', '')
salaries

40      74,138
43      68,129
92      60,114
118     68,123
125     54,102
129     76,140
132     65,125
140     85,159
141     80,105
161    120,145
162     80,120
170     60,114
179     59,110
202      48,95
226      48,93
262     59,110
290     62,114
319      48,95
332     70,132
357      52,99
371     67,117
386      48,93
388     65,119
399     75,143
421     65,124
430      43,86
447     74,124
450     76,142
493     61,109
543     65,119
560     63,120
568     75,143
591     76,145
617     65,124
631     55,105
635      57,80
640      43,86
655     79,147
670     74,124
673     76,142
743     61,109
744      42,79
758     74,137
759     57,109
784     65,126
803     58,104
836     65,124
853     55,105
857      57,80
883     79,147
907     74,124
911     76,142
948     62,113
Name: Salary Estimate, dtype: object

In [252]:
#se convierte la serie a una lista que almacena los salarios como string
salaries = salaries.to_list()
salaries

['74,138',
 '68,129',
 '60,114',
 '68,123',
 '54,102',
 '76,140',
 '65,125',
 '85,159',
 '80,105',
 '120,145',
 '80,120',
 '60,114',
 '59,110',
 '48,95',
 '48,93',
 '59,110',
 '62,114',
 '48,95',
 '70,132',
 '52,99',
 '67,117',
 '48,93',
 '65,119',
 '75,143',
 '65,124',
 '43,86',
 '74,124',
 '76,142',
 '61,109',
 '65,119',
 '63,120',
 '75,143',
 '76,145',
 '65,124',
 '55,105',
 '57,80',
 '43,86',
 '79,147',
 '74,124',
 '76,142',
 '61,109',
 '42,79',
 '74,137',
 '57,109',
 '65,126',
 '58,104',
 '65,124',
 '55,105',
 '57,80',
 '79,147',
 '74,124',
 '76,142',
 '62,113']

Se itera en la lista de strings para separarlos y transformarlos a valor numerico. El resultado es una lista que almacena listas con dos elementos numericos, donde el elemento en la posicion 0 de cada lista es el valor minimo y el elemento en la posicion 1 es el valor maximo.

In [253]:
def get_num(salaries):
  #se dividen los strings y se los almacena en una lista
  salaries = [s.split(',') for s in salaries]
  #se itera en la lista para transformar los strings a valor numerico
  salaries = [[int(s[0]), int(s[1])] for s in salaries]
  return salaries

salaries = get_num(salaries)
salaries

[[74, 138],
 [68, 129],
 [60, 114],
 [68, 123],
 [54, 102],
 [76, 140],
 [65, 125],
 [85, 159],
 [80, 105],
 [120, 145],
 [80, 120],
 [60, 114],
 [59, 110],
 [48, 95],
 [48, 93],
 [59, 110],
 [62, 114],
 [48, 95],
 [70, 132],
 [52, 99],
 [67, 117],
 [48, 93],
 [65, 119],
 [75, 143],
 [65, 124],
 [43, 86],
 [74, 124],
 [76, 142],
 [61, 109],
 [65, 119],
 [63, 120],
 [75, 143],
 [76, 145],
 [65, 124],
 [55, 105],
 [57, 80],
 [43, 86],
 [79, 147],
 [74, 124],
 [76, 142],
 [61, 109],
 [42, 79],
 [74, 137],
 [57, 109],
 [65, 126],
 [58, 104],
 [65, 124],
 [55, 105],
 [57, 80],
 [79, 147],
 [74, 124],
 [76, 142],
 [62, 113]]

Funcion que obtiene el valor promedio de los valores minimos

In [254]:
def avg_min(salaries):
  min_salaries = [s[0] for s in salaries]
  return (sum(min_salaries) / len(min_salaries))

round(avg_min(salaries), 1)

65.3

Funcion que obtiene el valor promedio de los valores maximos

In [255]:
def avg_max(salaries):
  max_salaries = [s[1] for s in salaries]
  return (sum(max_salaries) / len(max_salaries))

round(avg_max(salaries), 1)

118.0

Valor del salario promedio en base al promedio minimo y el promedio maximo

In [256]:
avg_salary = (avg_min(salaries) + avg_max(salaries)) / 2
round(avg_salary, 1)

91.7

**¿Cuales son los 5 trabajos mas demandados en USA?**

In [257]:
df.columns

Index(['Unnamed: 0.1', 'Unnamed: 0', 'Job Title', 'Salary Estimate', 'Rating',
       'Company Name', 'Location', 'Headquarters', 'Size', 'Founded',
       'Type of ownership', 'Industry', 'Sector', 'Revenue', 'Competitors'],
      dtype='object')

Nombre del empleo y su respectiva cantidad de ofertas

In [258]:
df['Job Title'].value_counts()

Job Title
Data Scientist                                                       178
Data Engineer                                                         68
Senior Data Scientist                                                 42
Data Analyst                                                          18
Senior Data Engineer                                                  17
                                                                    ...
Jr. Data Scientist                                                     1
Data Architect / Data Modeler                                          1
Data Scientists                                                        1
Associate Scientist / Sr. Associate Scientist, Antibody Discovery      1
Machine Learning Engineer (NLP)                                        1
Name: count, Length: 328, dtype: int64

Se crea un DataFrame con los datos obtenidos previamente

In [259]:
popular_jobs = pd.DataFrame(df['Job Title'].value_counts())
popular_jobs.columns

Index(['count'], dtype='object')

Se crea una nueva columna para el DataFrame que incluya el porcentaje y se limitan los resultados a cinco

In [260]:
popular_jobs['percentage'] = round((popular_jobs['count'] * 100) / popular_jobs['count'].sum(), 2)
popular_jobs.head(5)

                       count  percentage
Job Title
Data Scientist           178       18.62
Data Engineer             68        7.11
Senior Data Scientist     42        4.39
Data Analyst              18        1.88
Senior Data Engineer      17        1.78

Otra solucion

In [261]:
top5_jobs = (df['Job Title'].value_counts(normalize=True) *100).round(2).head(5)
top5_jobs

Job Title
Data Scientist           18.62
Data Engineer             7.11
Senior Data Scientist     4.39
Data Analyst              1.88
Senior Data Engineer      1.78
Name: proportion, dtype: float64

**¿Cual es el salario promedio de un Data Analyst?**

In [262]:
df.columns

Index(['Unnamed: 0.1', 'Unnamed: 0', 'Job Title', 'Salary Estimate', 'Rating',
       'Company Name', 'Location', 'Headquarters', 'Size', 'Founded',
       'Type of ownership', 'Industry', 'Sector', 'Revenue', 'Competitors'],
      dtype='object')

In [263]:
mask = (df['Job Title'] == 'Data Analyst') & (df['Salary Estimate'] != '-1')
df_data_analyst = df[mask]
df_data_analyst.shape[0]

15

In [264]:
df_data_analyst.value_counts('Salary Estimate')

Salary Estimate
$47K-$85K (Glassdoor est.)     2
$50K-$92K (Glassdoor est.)     2
$39K-$68K (Glassdoor est.)     1
$34K-$64K (Glassdoor est.)     1
$33K-$62K (Glassdoor est.)     1
$42K-$77K (Glassdoor est.)     1
$40K-$73K (Glassdoor est.)     1
$46K-$85K (Glassdoor est.)     1
$43K-$81K (Glassdoor est.)     1
$48K-$90K (Glassdoor est.)     1
$55K-$100K (Glassdoor est.)    1
$64K-$112K (Glassdoor est.)    1
$65K-$120K (Glassdoor est.)    1
Name: count, dtype: int64

In [265]:
salaries_data_analyst = pd.Series(df_data_analyst['Salary Estimate'])
salaries_data_analyst = salaries_data_analyst.str.replace('(Glassdoor est.)', '')
salaries_data_analyst = salaries_data_analyst.str.replace('K', '')
salaries_data_analyst = salaries_data_analyst.str.replace('$', '')
salaries_data_analyst = salaries_data_analyst.str.replace('-', ',')
salaries_data_analyst

13      46,85
41     64,112
91     55,100
93      39,68
109     40,73
142     43,81
264    65,120
270     33,62
274     48,90
275     34,64
410     50,92
600     50,92
609     42,77
616     47,85
832     47,85
Name: Salary Estimate, dtype: object

In [266]:
salaries_data_analyst = salaries_data_analyst.to_list()
salaries_data_analyst

['46,85 ',
 '64,112 ',
 '55,100 ',
 '39,68 ',
 '40,73 ',
 '43,81 ',
 '65,120 ',
 '33,62 ',
 '48,90 ',
 '34,64 ',
 '50,92 ',
 '50,92 ',
 '42,77 ',
 '47,85 ',
 '47,85 ']

In [267]:
get_num(salaries_data_analyst)

[[46, 85],
 [64, 112],
 [55, 100],
 [39, 68],
 [40, 73],
 [43, 81],
 [65, 120],
 [33, 62],
 [48, 90],
 [34, 64],
 [50, 92],
 [50, 92],
 [42, 77],
 [47, 85],
 [47, 85]]

In [268]:
round(avg_min(get_num(salaries_data_analyst)), 2)

46.87

In [269]:
round(avg_max(get_num(salaries_data_analyst)), 2)

85.73

In [270]:
round(avg_min(get_num(salaries_data_analyst)) + avg_max(get_num(salaries_data_analyst)) / 2, 2)

89.73