<a href="https://colab.research.google.com/github/mfernandezzz/Pruebas_Tecnicas/blob/main/pruebaTecnicaGlassdoorJobs.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [108]:
import pandas as pd
import numpy as np

In [109]:
df = pd.read_csv('/content/glassdoor_jobs_clean.csv')
df.head()

,Unnamed: 0.1,Unnamed: 0,Job Title,Salary Estimate,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors
0,0,0,Data Scientist,$53K-$91K (Glassdoor est.),3.8,Tecolote Research\n3.8,"Albuquerque, NM","Goleta, CA",501 to 1000 employees,1973,Company - Private,Aerospace & Defense,Aerospace & Defense,$50 to $100 million (USD),-1
1,1,1,Healthcare Data Scientist,$63K-$112K (Glassdoor est.),3.4,University of Maryland Medical System\n3.4,"Linthicum, MD","Baltimore, MD",10000+ employees,1984,Other Organization,Health Care Services & Hospitals,Health Care,$2 to $5 billion (USD),-1
2,2,2,Data Scientist,$80K-$90K (Glassdoor est.),4.8,KnowBe4\n4.8,"Clearwater, FL","Clearwater, FL",501 to 1000 employees,2010,Company - Private,Security Services,Business Services,$100 to $500 million (USD),-1
3,3,3,Data Scientist,$56K-$97K (Glassdoor est.),3.8,PNNL\n3.8,"Richland, WA","Richland, WA",1001 to 5000 employees,1965,Government,Energy,"Oil, Gas, Energy & Utilities",$500 million to $1 billion (USD),"Oak Ridge National Laboratory, National Renewa..."
4,4,4,Data Scientist,$86K-$143K (Glassdoor est.),2.9,Affinity Solutions\n2.9,"New York, NY","New York, NY",51 to 200 employees,1998,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable,"Commerce Signals, Cardlytics, Yodlee"

In [110]:
df.drop(columns='Unnamed: 0.1', inplace=True)
df.head(4)

,Unnamed: 0,Job Title,Salary Estimate,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors
0,0,Data Scientist,$53K-$91K (Glassdoor est.),3.8,Tecolote Research\n3.8,"Albuquerque, NM","Goleta, CA",501 to 1000 employees,1973,Company - Private,Aerospace & Defense,Aerospace & Defense,$50 to $100 million (USD),-1
1,1,Healthcare Data Scientist,$63K-$112K (Glassdoor est.),3.4,University of Maryland Medical System\n3.4,"Linthicum, MD","Baltimore, MD",10000+ employees,1984,Other Organization,Health Care Services & Hospitals,Health Care,$2 to $5 billion (USD),-1
2,2,Data Scientist,$80K-$90K (Glassdoor est.),4.8,KnowBe4\n4.8,"Clearwater, FL","Clearwater, FL",501 to 1000 employees,2010,Company - Private,Security Services,Business Services,$100 to $500 million (USD),-1
3,3,Data Scientist,$56K-$97K (Glassdoor est.),3.8,PNNL\n3.8,"Richland, WA","Richland, WA",1001 to 5000 employees,1965,Government,Energy,"Oil, Gas, Energy & Utilities",$500 million to $1 billion (USD),"Oak Ridge National Laboratory, National Renewa..."

In [111]:
df.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 956 entries, 0 to 955
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         956 non-null    int64
 1   Job Title          956 non-null    object
 2   Salary Estimate    956 non-null    object
 3   Rating             956 non-null    float64
 4   Company Name       956 non-null    object
 5   Location           956 non-null    object
 6   Headquarters       956 non-null    object
 7   Size               956 non-null    object
 8   Founded            956 non-null    int64
 9   Type of ownership  956 non-null    object
 10  Industry           956 non-null    object
 11  Sector             956 non-null    object
 12  Revenue            956 non-null    object
 13  Competitors        956 non-null    object
dtypes: float64(1), int64(2), object(11)
memory usage: 721.8 KB

In [112]:
df['Job Title'].value_counts().head(4)

Job Title
Data Scientist           178
Data Engineer             68
Senior Data Scientist     42
Data Analyst              18
Name: count, dtype: int64

In [113]:
# df['Job Title'].unique()

**¿Cual es el salario promedio anual de un Data Engineer?**

In [114]:
data_engineer = df.loc[(df['Job Title'] == 'Data Engineer') & (df['Salary Estimate'] != '-1')]
data_engineer.shape

(53, 14)

In [115]:
data_engineer['Salary Estimate'].unique()

array(['$74K-$138K (Glassdoor est.)', '$68K-$129K (Glassdoor est.)',
       '$60K-$114K (Glassdoor est.)', '$68K-$123K (Glassdoor est.)',
       '$54K-$102K (Glassdoor est.)', '$76K-$140K (Glassdoor est.)',
       '$65K-$125K (Glassdoor est.)', '$85K-$159K (Glassdoor est.)',
       '$80K-$105K(Employer est.)',
       'Employer Provided Salary:$120K-$145K',
       '$80K-$120K (Glassdoor est.)', '$59K-$110K (Glassdoor est.)',
       '$48K-$95K (Glassdoor est.)', '$48K-$93K (Glassdoor est.)',
       '$62K-$114K (Glassdoor est.)', '$70K-$132K (Glassdoor est.)',
       '$52K-$99K (Glassdoor est.)', '$67K-$117K (Glassdoor est.)',
       '$65K-$119K (Glassdoor est.)', '$75K-$143K (Glassdoor est.)',
       '$65K-$124K (Glassdoor est.)', '$43K-$86K (Glassdoor est.)',
       '$74K-$124K (Glassdoor est.)', '$76K-$142K (Glassdoor est.)',
       '$61K-$109K (Glassdoor est.)', '$63K-$120K (Glassdoor est.)',
       '$76K-$145K (Glassdoor est.)', '$55K-$105K (Glassdoor est.)',
       '$57K-$80K (Glassdoor est.)', '$79K-$147K (Glassdoor est.)',
       '$42K-$79K (Glassdoor est.)', '$74K-$137K (Glassdoor est.)',
       '$57K-$109K (Glassdoor est.)', '$65K-$126K (Glassdoor est.)',
       '$58K-$104K (Glassdoor est.)', '$62K-$113K (Glassdoor est.)'],
      dtype=object)

In [116]:
data_engineer['Salary Estimate'] = (
    data_engineer['Salary Estimate'].astype(str)
    .str.strip()
    .str.replace('(Glassdoor est.)', '')
    .str.replace('Employer Provided Salary:', '')
    .str.replace('Employer est.', '')
    .str.replace('K', '000')
    .str.replace('$', '')
    .str.replace('()', '')
    .str.replace(' ', '')
    )

data_engineer['Salary Estimate'].unique()

/tmp/ipykernel_1569/649926453.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_engineer['Salary Estimate'] = (

array(['74000-138000', '68000-129000', '60000-114000', '68000-123000',
       '54000-102000', '76000-140000', '65000-125000', '85000-159000',
       '80000-105000', '120000-145000', '80000-120000', '59000-110000',
       '48000-95000', '48000-93000', '62000-114000', '70000-132000',
       '52000-99000', '67000-117000', '65000-119000', '75000-143000',
       '65000-124000', '43000-86000', '74000-124000', '76000-142000',
       '61000-109000', '63000-120000', '76000-145000', '55000-105000',
       '57000-80000', '79000-147000', '42000-79000', '74000-137000',
       '57000-109000', '65000-126000', '58000-104000', '62000-113000'],
      dtype=object)

In [117]:
salaries = data_engineer['Salary Estimate'].str.split('-')
salaries.head()

40     [74000, 138000]
43     [68000, 129000]
92     [60000, 114000]
118    [68000, 123000]
125    [54000, 102000]
Name: Salary Estimate, dtype: object

In [118]:
def min_max_values(salaries):
  min_salary, max_salary = [], []
  for s in salaries:
    min_salary.append(s[0])
    max_salary.append(s[1])
  return {
      'min_salaries': min_salary,
      'max_salaries': max_salary
  }

# min_max_values(salaries)

range_salaries = pd.DataFrame(min_max_values(salaries))
range_salaries.head()

  min_salaries max_salaries
0        74000       138000
1        68000       129000
2        60000       114000
3        68000       123000
4        54000       102000

In [119]:
range_salaries.dtypes

min_salaries    object
max_salaries    object
dtype: object

In [120]:
range_salaries['min_salaries'] = range_salaries['min_salaries'].astype(int)
range_salaries['max_salaries'] = range_salaries['max_salaries'].astype(int)
range_salaries.dtypes

min_salaries    int64
max_salaries    int64
dtype: object

In [121]:
range_salaries['avg'] = ((range_salaries['min_salaries']) + (range_salaries['max_salaries'])) / 2
range_salaries.head()

   min_salaries  max_salaries       avg
0         74000        138000  106000.0
1         68000        129000   98500.0
2         60000        114000   87000.0
3         68000        123000   95500.0
4         54000        102000   78000.0

In [122]:
data_engineer_avg_salary = sum(range_salaries['avg']) / (range_salaries.shape[0])
f'El salario promedio anual de un Data Engineer es de {round(data_engineer_avg_salary, 2)} dolares.'

'El salario promedio anual de un Data Engineer es de 91660.38 dolares.'

In [123]:
# not accurate
avg_min_sal = range_salaries['min_salaries'].sum() / range_salaries.shape[0]
avg_max_sal = range_salaries['max_salaries'].sum() / range_salaries.shape[0]
xtwo = ((avg_min_sal) + (avg_max_sal) / 2)
xtwo

np.float64(124330.18867924529)

**¿Cual es el salario promedio de todas las profesiones que incluyan el termino Data Engineer?**

In [124]:
df.loc[df['Job Title'].str.contains('Data Engineer'), 'Salary Estimate'].shape

(158,)

In [125]:
df.loc[(df['Job Title'].str.contains('Data Engineer')) & (df['Salary Estimate'] == '-1')].shape

(39, 14)

In [126]:
all_data_engineer = df.loc[(df['Job Title'].str.contains('Data Engineer') & (df['Salary Estimate'] != '-1'))]
all_data_engineer.shape

(119, 14)

In [127]:
all_data_engineer.head(4)

,Unnamed: 0,Job Title,Salary Estimate,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors
15,15,Data Engineer I,$102K-$190K (Glassdoor est.),3.6,Audible\n3.6,"Newark, NJ","Newark, NJ",1001 to 5000 employees,1995,Subsidiary or Business Segment,Motion Picture Production & Distribution,Media,Unknown / Non-Applicable,-1
40,40,Data Engineer,$74K-$138K (Glassdoor est.),3.5,Lancer Insurance\n3.5,"Long Beach, NY","Long Beach, NY",201 to 500 employees,1985,Company - Private,Insurance Carriers,Insurance,$100 to $500 million (USD),-1
43,43,Data Engineer,$68K-$129K (Glassdoor est.),3.6,Persivia\n3.6,"Marlborough, MA","Lowell, MA",1 to 50 employees,-1,Company - Private,-1,-1,Less than $1 million (USD),-1
92,92,Data Engineer,$60K-$114K (Glassdoor est.),4.0,Excella Consulting\n4.0,"Arlington, VA","Arlington, VA",201 to 500 employees,2002,Company - Private,Consulting,Business Services,$50 to $100 million (USD),-1

In [128]:
all_data_engineer['Salary Estimate'].unique()

array(['$102K-$190K (Glassdoor est.)', '$74K-$138K (Glassdoor est.)',
       '$68K-$129K (Glassdoor est.)', '$60K-$114K (Glassdoor est.)',
       '$68K-$123K (Glassdoor est.)', '$54K-$102K (Glassdoor est.)',
       '$76K-$140K (Glassdoor est.)', '$65K-$125K (Glassdoor est.)',
       '$95K-$173K (Glassdoor est.)', '$85K-$159K (Glassdoor est.)',
       '$80K-$105K(Employer est.)',
       'Employer Provided Salary:$120K-$145K',
       '$80K-$120K (Glassdoor est.)', '$59K-$115K (Glassdoor est.)',
       '$77K-$136K (Glassdoor est.)', '$59K-$110K (Glassdoor est.)',
       '$74K-$140K (Glassdoor est.)', '$48K-$95K (Glassdoor est.)',
       '$48K-$93K (Glassdoor est.)', '$190K-$220K(Employer est.)',
       '$69K-$127K (Glassdoor est.)', '$75K-$140K (Glassdoor est.)',
       '$62K-$114K (Glassdoor est.)', '$71K-$129K (Glassdoor est.)',
       '$67K-$119K (Glassdoor est.)', '$70K-$132K (Glassdoor est.)',
       '$54K-$101K (Glassdoor est.)', '$52K-$99K (Glassdoor est.)',
       '$71K-$134K (Glassdoor est.)', '$67K-$117K (Glassdoor est.)',
       '$116K-$209K (Glassdoor est.)', '$62K-$119K (Glassdoor est.)',
       '$65K-$119K (Glassdoor est.)', '$75K-$143K (Glassdoor est.)',
       '$105K-$194K (Glassdoor est.)', '$45K-$86K (Glassdoor est.)',
       '$80K-$148K (Glassdoor est.)', '$65K-$124K (Glassdoor est.)',
       '$43K-$86K (Glassdoor est.)', '$113K-$196K (Glassdoor est.)',
       '$74K-$124K (Glassdoor est.)', '$76K-$142K (Glassdoor est.)',
       '$87K-$158K (Glassdoor est.)', '$61K-$119K (Glassdoor est.)',
       '$78K-$147K (Glassdoor est.)', '$90K-$110K(Employer est.)',
       '$61K-$109K (Glassdoor est.)', '$97K-$180K (Glassdoor est.)',
       '$121K-$203K (Glassdoor est.)', '$83K-$148K (Glassdoor est.)',
       '$66K-$123K (Glassdoor est.)', '$97K-$181K (Glassdoor est.)',
       '$100K-$173K (Glassdoor est.)', '$63K-$120K (Glassdoor est.)',
       '$126K-$228K (Glassdoor est.)', '$76K-$145K (Glassdoor est.)',
       '$49K-$97K (Glassdoor est.)', '$55K-$105K (Glassdoor est.)',
       '$57K-$80K (Glassdoor est.)', '$59K-$112K (Glassdoor est.)',
       '$79K-$147K (Glassdoor est.)', '$72K-$133K (Glassdoor est.)',
       '$44K-$86K (Glassdoor est.)', '$67K-$127K (Glassdoor est.)',
       '$42K-$79K (Glassdoor est.)', '$84K-$153K (Glassdoor est.)',
       '$44K-$73K (Glassdoor est.)', '$74K-$137K (Glassdoor est.)',
       '$57K-$109K (Glassdoor est.)', '$65K-$126K (Glassdoor est.)',
       '$58K-$104K (Glassdoor est.)', '$71K-$135K (Glassdoor est.)',
       '$62K-$113K (Glassdoor est.)'], dtype=object)

In [129]:
all_data_engineer['Salary Estimate'] = (all_data_engineer['Salary Estimate']
                            .astype(str)
                            .str.strip()
                            .str.replace('(Glassdoor est.)', '')
                            .str.replace('Employer Provided Salary:', '')
                            .str.replace('(Employer est.)', '')
                            .str.replace('K', '000')
                            .str.replace('$', '')
                            .str.replace(' ', '')
                            )
all_data_engineer['Salary Estimate'].unique()

/tmp/ipykernel_1569/1204175006.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  all_data_engineer['Salary Estimate'] = (all_data_engineer['Salary Estimate']

array(['102000-190000', '74000-138000', '68000-129000', '60000-114000',
       '68000-123000', '54000-102000', '76000-140000', '65000-125000',
       '95000-173000', '85000-159000', '80000-105000', '120000-145000',
       '80000-120000', '59000-115000', '77000-136000', '59000-110000',
       '74000-140000', '48000-95000', '48000-93000', '190000-220000',
       '69000-127000', '75000-140000', '62000-114000', '71000-129000',
       '67000-119000', '70000-132000', '54000-101000', '52000-99000',
       '71000-134000', '67000-117000', '116000-209000', '62000-119000',
       '65000-119000', '75000-143000', '105000-194000', '45000-86000',
       '80000-148000', '65000-124000', '43000-86000', '113000-196000',
       '74000-124000', '76000-142000', '87000-158000', '61000-119000',
       '78000-147000', '90000-110000', '61000-109000', '97000-180000',
       '121000-203000', '83000-148000', '66000-123000', '97000-181000',
       '100000-173000', '63000-120000', '126000-228000', '76000-145000',
       '49000-97000', '55000-105000', '57000-80000', '59000-112000',
       '79000-147000', '72000-133000', '44000-86000', '67000-127000',
       '42000-79000', '84000-153000', '44000-73000', '74000-137000',
       '57000-109000', '65000-126000', '58000-104000', '71000-135000',
       '62000-113000'], dtype=object)

In [130]:
all_data_engineer_salaries = all_data_engineer['Salary Estimate'].str.split('-')
all_data_engineer_salaries.head()

15     [102000, 190000]
40      [74000, 138000]
43      [68000, 129000]
92      [60000, 114000]
118     [68000, 123000]
Name: Salary Estimate, dtype: object

In [166]:
de_sal_ranges = pd.DataFrame(min_max_values(all_data_engineer_salaries))
de_sal_ranges.head()

  min_salaries max_salaries
0       102000       190000
1        74000       138000
2        68000       129000
3        60000       114000
4        68000       123000

In [132]:
de_sal_ranges.dtypes

min_salaries    object
max_salaries    object
dtype: object

In [133]:
de_sal_ranges['min_salaries'] = de_sal_ranges['min_salaries'].astype(int)
de_sal_ranges['max_salaries'] = de_sal_ranges['max_salaries'].astype(int)
de_sal_ranges.dtypes

min_salaries    int64
max_salaries    int64
dtype: object

In [134]:
de_sal_ranges['avg'] = (de_sal_ranges['min_salaries'] + de_sal_ranges['max_salaries']) / 2
de_sal_ranges.head()

   min_salaries  max_salaries       avg
0        102000        190000  146000.0
1         74000        138000  106000.0
2         68000        129000   98500.0
3         60000        114000   87000.0
4         68000        123000   95500.0

In [135]:
data_engineer_salary_avg = de_sal_ranges['avg'].sum() / de_sal_ranges.shape[0]
f'El salario promedio anual de un Data Engineer es de {round(data_engineer_salary_avg, 2)} dolares'

'El salario promedio anual de un Data Engineer es de 105403.36 dolares'

**¿Cuales son los 5 trabajos mas demandados en USA?**

In [136]:
df.columns

Index(['Unnamed: 0', 'Job Title', 'Salary Estimate', 'Rating', 'Company Name',
       'Location', 'Headquarters', 'Size', 'Founded', 'Type of ownership',
       'Industry', 'Sector', 'Revenue', 'Competitors'],
      dtype='object')

In [137]:
df['Job Title'].value_counts().head()

Job Title
Data Scientist           178
Data Engineer             68
Senior Data Scientist     42
Data Analyst              18
Senior Data Engineer      17
Name: count, dtype: int64

In [138]:
popular_jobs = pd.DataFrame(df['Job Title'].value_counts()).reset_index()
popular_jobs.rename(columns={'count': 'Total Jobs'}, inplace=True)
popular_jobs.head()

               Job Title  Total Jobs
0         Data Scientist         178
1          Data Engineer          68
2  Senior Data Scientist          42
3           Data Analyst          18
4   Senior Data Engineer          17

In [139]:
popular_jobs['%'] = round((popular_jobs['Total Jobs'] * 100) / popular_jobs['Total Jobs'].sum(), 2)
popular_jobs.head()

               Job Title  Total Jobs      %
0         Data Scientist         178  18.62
1          Data Engineer          68   7.11
2  Senior Data Scientist          42   4.39
3           Data Analyst          18   1.88
4   Senior Data Engineer          17   1.78

Otra solucion

In [140]:
top5_jobs = (df['Job Title'].value_counts(normalize=True)*100).round(2).reset_index()
top5_jobs.rename(columns={'proportion': '%'}, inplace=True)
top5_jobs.head()

               Job Title      %
0         Data Scientist  18.62
1          Data Engineer   7.11
2  Senior Data Scientist   4.39
3           Data Analyst   1.88
4   Senior Data Engineer   1.78

**¿Cual es el salario promedio de todas las profesiones de Data Analyst?**

In [141]:
df.columns

Index(['Unnamed: 0', 'Job Title', 'Salary Estimate', 'Rating', 'Company Name',
       'Location', 'Headquarters', 'Size', 'Founded', 'Type of ownership',
       'Industry', 'Sector', 'Revenue', 'Competitors'],
      dtype='object')

In [142]:
df.loc[df['Job Title'].str.contains('Data Analyst')].shape

(107, 14)

In [143]:
df.loc[(df['Job Title'].str.contains('Data Analyst')) & (df['Salary Estimate'] == '-1')].shape

(8, 14)

In [144]:
all_data_analyst = df.loc[(df['Job Title'].str.contains('Data Analyst')) & (df['Salary Estimate'] != '-1')]
all_data_analyst.shape

(99, 14)

In [145]:
all_data_analyst.head()

,Unnamed: 0,Job Title,Salary Estimate,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors
13,13,Data Analyst,$46K-$85K (Glassdoor est.),4.1,Yesler\n4.1,"Seattle, WA","Seattle, WA",201 to 500 employees,2012,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable,-1
28,28,Associate Data Analyst,$34K-$61K (Glassdoor est.),3.7,The Hanover Insurance Group\n3.7,"Worcester, MA","Worcester, MA",5001 to 10000 employees,1852,Company - Public,Insurance Carriers,Insurance,$5 to $10 billion (USD),-1
36,36,Web Data Analyst,$77K-$135K (Glassdoor est.),4.2,Clarity Insights\n4.2,"San Jose, CA","Chicago, IL",201 to 500 employees,2008,Company - Private,IT Services,Information Technology,Unknown / Non-Applicable,-1
41,41,Data Analyst,$64K-$112K (Glassdoor est.),4.2,Sauce Labs\n4.2,"San Francisco, CA","San Francisco, CA",201 to 500 employees,2008,Company - Private,IT Services,Information Technology,$50 to $100 million (USD),"BrowserStack, Selenium Master, Perfecto Mobile"
50,50,Associate Data Analyst,$20K-$39K (Glassdoor est.),3.1,Intrado\n3.1,"Longmont, CO","Omaha, NE",5001 to 10000 employees,1986,Company - Private,Enterprise Software & Network Solutions,Information Technology,$2 to $5 billion (USD),-1

In [146]:
all_data_analyst['Salary Estimate'].unique()

array(['$46K-$85K (Glassdoor est.)', '$34K-$61K (Glassdoor est.)',
       '$77K-$135K (Glassdoor est.)', '$64K-$112K (Glassdoor est.)',
       '$20K-$39K (Glassdoor est.)', '$37K-$76K (Glassdoor est.)',
       '$55K-$100K (Glassdoor est.)', '$39K-$68K (Glassdoor est.)',
       '$34K-$62K (Glassdoor est.)', '$52K-$93K (Glassdoor est.)',
       '$40K-$73K (Glassdoor est.)', '$41K-$72K (Glassdoor est.)',
       '$39K-$71K (Glassdoor est.)', '$43K-$81K (Glassdoor est.)',
       '$71K-$136K (Glassdoor est.)', '$44K-$78K (Glassdoor est.)',
       '$43K-$80K (Glassdoor est.)', '$31K-$72K (Glassdoor est.)',
       '$42K-$76K (Glassdoor est.)', '$35K-$62K (Glassdoor est.)',
       '$44K-$86K (Glassdoor est.)', '$65K-$120K (Glassdoor est.)',
       '$33K-$62K (Glassdoor est.)', '$48K-$90K (Glassdoor est.)',
       '$34K-$64K (Glassdoor est.)', '$55K-$97K (Glassdoor est.)',
       '$74K-$126K (Glassdoor est.)', '$37K-$63K (Glassdoor est.)',
       '$45K-$82K (Glassdoor est.)', '$42K-$74K (Glassdoor est.)',
       '$60K-$102K (Glassdoor est.)', '$55K-$99K (Glassdoor est.)',
       '$52K-$89K (Glassdoor est.)', '$31K-$57K (Glassdoor est.)',
       '$36K-$62K (Glassdoor est.)', '$50K-$92K (Glassdoor est.)',
       '$42K-$80K (Glassdoor est.)', '$32K-$59K (Glassdoor est.)',
       '$43K-$77K (Glassdoor est.)', '$65K-$110K (Glassdoor est.)',
       '$31K-$55K (Glassdoor est.)', '$48K-$85K (Glassdoor est.)',
       '$10-$17 Per Hour(Glassdoor est.)', '$49K-$76K (Glassdoor est.)',
       '$54K-$92K (Glassdoor est.)', '$42K-$77K (Glassdoor est.)',
       '$47K-$85K (Glassdoor est.)', '$35K-$65K (Glassdoor est.)',
       '$90K-$157K (Glassdoor est.)', '$32K-$62K (Glassdoor est.)',
       '$39K-$69K (Glassdoor est.)', '$27K-$48K (Glassdoor est.)',
       '$36K-$71K (Glassdoor est.)', '$99K-$178K (Glassdoor est.)',
       '$53K-$91K (Glassdoor est.)', '$33K-$61K (Glassdoor est.)',
       '$69K-$119K (Glassdoor est.)', '$90K-$153K (Glassdoor est.)',
       '$58K-$108K (Glassdoor est.)', '$61K-$110K (Glassdoor est.)',
       '$32K-$57K (Glassdoor est.)', '$79K-$136K (Glassdoor est.)',
       '$50K-$89K (Glassdoor est.)'], dtype=object)

In [147]:
all_data_analyst.loc[all_data_analyst['Salary Estimate'] == '$10-$17 Per Hour(Glassdoor est.)']

,Unnamed: 0,Job Title,Salary Estimate,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors
523,523,"Senior Operations Data Analyst, Call Center Op...",$10-$17 Per Hour(Glassdoor est.),2.7,FLEETCOR\n2.7,"Nashville, TN","Peachtree Corners, GA",5001 to 10000 employees,2000,Company - Public,Financial Transaction Processing,Finance,$2 to $5 billion (USD),-1
787,787,"Senior Operations Data Analyst, Call Center Op...",$10-$17 Per Hour(Glassdoor est.),2.7,FLEETCOR\n2.7,"Nashville, TN","Peachtree Corners, GA",5001 to 10000 employees,2000,Company - Public,Financial Transaction Processing,Finance,$2 to $5 billion (USD),-1

In [148]:
all_data_analyst = all_data_analyst[~(all_data_analyst['Salary Estimate'] == '$10-$17 Per Hour(Glassdoor est.)')]
all_data_analyst.shape

(97, 14)

In [149]:
all_data_analyst['Salary Estimate'] = (all_data_analyst['Salary Estimate']
                                      .astype(str)
                                      .str.strip()
                                      .str.replace('(Glassdoor est.)', '')
                                      .str.replace('Per Hour', '')
                                      .str.replace('K', '000')
                                      .str.replace('$', '')
                                      .str.replace(' ', '')
                                      )
all_data_analyst['Salary Estimate'].unique()

array(['46000-85000', '34000-61000', '77000-135000', '64000-112000',
       '20000-39000', '37000-76000', '55000-100000', '39000-68000',
       '34000-62000', '52000-93000', '40000-73000', '41000-72000',
       '39000-71000', '43000-81000', '71000-136000', '44000-78000',
       '43000-80000', '31000-72000', '42000-76000', '35000-62000',
       '44000-86000', '65000-120000', '33000-62000', '48000-90000',
       '34000-64000', '55000-97000', '74000-126000', '37000-63000',
       '45000-82000', '42000-74000', '60000-102000', '55000-99000',
       '52000-89000', '31000-57000', '36000-62000', '50000-92000',
       '42000-80000', '32000-59000', '43000-77000', '65000-110000',
       '31000-55000', '48000-85000', '49000-76000', '54000-92000',
       '42000-77000', '47000-85000', '35000-65000', '90000-157000',
       '32000-62000', '39000-69000', '27000-48000', '36000-71000',
       '99000-178000', '53000-91000', '33000-61000', '69000-119000',
       '90000-153000', '58000-108000', '61000-110000', '32000-57000',
       '79000-136000', '50000-89000'], dtype=object)

In [150]:
all_data_analyst_salaries = all_data_analyst['Salary Estimate'].str.split('-')
all_data_analyst_salaries.head()

13     [46000, 85000]
28     [34000, 61000]
36    [77000, 135000]
41    [64000, 112000]
50     [20000, 39000]
Name: Salary Estimate, dtype: object

In [151]:
def get_salaries(salaries):
  min_salaries, max_salaries = [], []
  for s in salaries:
    min_salaries.append(s[0])
    max_salaries.append(s[1])
  return {
      'min_salaries': min_salaries,
      'max_salaries': max_salaries
  }

# get_salaries(da_salaries)

all_data_analyst_sal_range = pd.DataFrame(get_salaries(all_data_analyst_salaries))
all_data_analyst_sal_range.head()

  min_salaries max_salaries
0        46000        85000
1        34000        61000
2        77000       135000
3        64000       112000
4        20000        39000

In [152]:
all_data_analyst_sal_range.dtypes

min_salaries    object
max_salaries    object
dtype: object

In [153]:
all_data_analyst_sal_range['min_salaries'] = all_data_analyst_sal_range['min_salaries'].astype(int)
all_data_analyst_sal_range['max_salaries'] = all_data_analyst_sal_range['max_salaries'].astype(int)
all_data_analyst_sal_range.dtypes

min_salaries    int64
max_salaries    int64
dtype: object

In [154]:
all_data_analyst_sal_range['avg'] = (all_data_analyst_sal_range['min_salaries'] + all_data_analyst_sal_range['max_salaries']) / 2
all_data_analyst_sal_range.head()

   min_salaries  max_salaries       avg
0         46000         85000   65500.0
1         34000         61000   47500.0
2         77000        135000  106000.0
3         64000        112000   88000.0
4         20000         39000   29500.0

In [155]:
all_data_analyst_avg_salary = all_data_analyst_sal_range['avg'].sum() / all_data_analyst_sal_range.shape[0]
f'El salario promedio anual de un Analista de datos es de {round(all_data_analyst_avg_salary, 2)} dolares.'

'El salario promedio anual de un Analista de datos es de 65675.26 dolares.'

**¿Cual es el salario promedio anual de un Data Analyst?**

In [156]:
data_analyst = df.loc[(df['Job Title'] == 'Data Analyst') & (df['Salary Estimate'] != '-1')]
data_analyst.head()

,Unnamed: 0,Job Title,Salary Estimate,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors
13,13,Data Analyst,$46K-$85K (Glassdoor est.),4.1,Yesler\n4.1,"Seattle, WA","Seattle, WA",201 to 500 employees,2012,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable,-1
41,41,Data Analyst,$64K-$112K (Glassdoor est.),4.2,Sauce Labs\n4.2,"San Francisco, CA","San Francisco, CA",201 to 500 employees,2008,Company - Private,IT Services,Information Technology,$50 to $100 million (USD),"BrowserStack, Selenium Master, Perfecto Mobile"
91,91,Data Analyst,$55K-$100K (Glassdoor est.),4.3,Productive Edge\n4.3,"Chicago, IL","Chicago, IL",51 to 200 employees,2008,Company - Private,Computer Hardware & Software,Information Technology,$10 to $25 million (USD),"Numerator, Rise Interactive, Salom"
93,93,Data Analyst,$39K-$68K (Glassdoor est.),4.4,Gensco\n4.4,"Tacoma, WA","Tacoma, WA",501 to 1000 employees,1948,Company - Private,Wholesale,Business Services,$100 to $500 million (USD),-1
109,109,Data Analyst,$40K-$73K (Glassdoor est.),3.1,DentaQuest\n3.1,"Milwaukee, WI","Boston, MA",1001 to 5000 employees,2001,Company - Private,Insurance Carriers,Insurance,$2 to $5 billion (USD),"MCNA Dental Plans, United Concordia, Delta Den..."

In [157]:
data_analyst.shape

(15, 14)

In [158]:
data_analyst['Salary Estimate'].unique()

array(['$46K-$85K (Glassdoor est.)', '$64K-$112K (Glassdoor est.)',
       '$55K-$100K (Glassdoor est.)', '$39K-$68K (Glassdoor est.)',
       '$40K-$73K (Glassdoor est.)', '$43K-$81K (Glassdoor est.)',
       '$65K-$120K (Glassdoor est.)', '$33K-$62K (Glassdoor est.)',
       '$48K-$90K (Glassdoor est.)', '$34K-$64K (Glassdoor est.)',
       '$50K-$92K (Glassdoor est.)', '$42K-$77K (Glassdoor est.)',
       '$47K-$85K (Glassdoor est.)'], dtype=object)

In [159]:
data_analyst['Salary Estimate'] = (data_analyst['Salary Estimate']
                            .astype(str)
                            .str.strip()
                            .str.replace('(Glassdoor est.)', '')
                            .str.replace('K', '000')
                            .str.replace('$', '')
                            .str.replace(' ', '')
                            )

data_analyst['Salary Estimate'].unique()

/tmp/ipykernel_1569/1231206452.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_analyst['Salary Estimate'] = (data_analyst['Salary Estimate']

array(['46000-85000', '64000-112000', '55000-100000', '39000-68000',
       '40000-73000', '43000-81000', '65000-120000', '33000-62000',
       '48000-90000', '34000-64000', '50000-92000', '42000-77000',
       '47000-85000'], dtype=object)

In [160]:
data_analyst_salaries = data_analyst['Salary Estimate'].str.split('-')
data_analyst_salaries.head()

13      [46000, 85000]
41     [64000, 112000]
91     [55000, 100000]
93      [39000, 68000]
109     [40000, 73000]
Name: Salary Estimate, dtype: object

In [161]:
data_analyst_salaries_ranges = pd.DataFrame(get_salaries(data_analyst_salaries))
data_analyst_salaries_ranges.head()

  min_salaries max_salaries
0        46000        85000
1        64000       112000
2        55000       100000
3        39000        68000
4        40000        73000

In [162]:
data_analyst_salaries_ranges.dtypes

min_salaries    object
max_salaries    object
dtype: object

In [163]:
data_analyst_salaries_ranges['min_salaries'] = data_analyst_salaries_ranges['min_salaries'].astype(int)
data_analyst_salaries_ranges['max_salaries'] = data_analyst_salaries_ranges['max_salaries'].astype(int)
data_analyst_salaries_ranges.dtypes

min_salaries    int64
max_salaries    int64
dtype: object

In [164]:
data_analyst_salaries_ranges['avg'] = ((data_analyst_salaries_ranges['min_salaries']) + (data_analyst_salaries_ranges['max_salaries'])) / 2
data_analyst_salaries_ranges.head()

   min_salaries  max_salaries      avg
0         46000         85000  65500.0
1         64000        112000  88000.0
2         55000        100000  77500.0
3         39000         68000  53500.0
4         40000         73000  56500.0

In [165]:
avg_salary_data_analyst = data_analyst_salaries_ranges['avg'].sum() / data_analyst_salaries_ranges.shape[0]
f'El salario promedio anual para un Analista de Datos es de {round(avg_salary_data_analyst, 2)} dolares.'

'El salario promedio anual para un Analista de Datos es de 66300.0 dolares.'