<a href="https://colab.research.google.com/github/mfernandezzz/Pruebas_Tecnicas/blob/main/pruebaTecnicaSocialMedia.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**¿Con que edad se consumen mas las redes sociales?**

Obtener el promedio de edad y de cantidad de horas de uso de las redes sociales. Tomar como referencia los valores de la columna Daily_Screen_Time_Hours y la columna edad.

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv('/content/social_media_mental_health.csv')
df.head()

,User_ID,Age,Gender,User_Archetype,Primary_Platform,Daily_Screen_Time_Hours,Dominant_Content_Type,Activity_Type,Late_Night_Usage,Social_Comparison_Trigger,Sleep_Duration_Hours,GAD_7_Score,GAD_7_Severity,PHQ_9_Score,PHQ_9_Severity
0,U-b23639d2,18,Male,Hyper-Connected,Twitter/X,8.50,Gaming,Active,0,0,3.9,9,Mild,5,Mild
1,U-e7778765,20,Male,Digital Minimalist,TikTok,0.50,Gaming,Active,0,0,5.5,0,Minimal,8,Mild
2,U-76749892,18,Female,Digital Minimalist,Snapchat,0.91,Gaming,Active,0,0,8.9,1,Minimal,3,None-Minimal
3,U-dcbbd7f9,18,Female,Hyper-Connected,Snapchat,7.43,Gaming,Active,1,0,6.2,13,Moderate,0,None-Minimal
4,U-9e1ba278,18,Male,Hyper-Connected,LinkedIn,4.94,Entertainment/Comedy,Active,1,0,5.3,13,Moderate,10,Moderate

In [ ]:
df.shape[0]

8000

In [ ]:
df['User_ID'].duplicated().value_counts()

User_ID
False    8000
Name: count, dtype: int64

Se agrupa por edad y se calcula el tiempo de consumo diario

In [ ]:
result = df.groupby('Age')['Daily_Screen_Time_Hours'].mean()

In [ ]:
result.idxmax()

np.int64(22)

In [ ]:
round(result.max(), 1)

4.4

In [ ]:
f'La edad en la que se consumen mas redes sociales es {result.idxmax()} años y el promedio de horas diario es de {round(result.max(), 1)} horas'

'La edad en la que se consumen mas redes sociales es 22 años y el promedio de horas diario es de 4.4 horas'

In [ ]:
df['Primary_Platform'].value_counts()

Primary_Platform
TikTok       1185
Instagram    1165
Twitter/X    1147
YouTube      1134
LinkedIn     1132
Snapchat     1124
Facebook     1113
Name: count, dtype: int64

In [ ]:
df['Primary_Platform'].unique()

array(['Twitter/X', 'TikTok', 'Snapchat', 'LinkedIn', 'YouTube',
       'Facebook', 'Instagram'], dtype=object)

**Obtener la edad en la que se consume mas cada red social y su mayor promedio de uso diario asociado.**

In [ ]:
mask = df['Primary_Platform'] == 'Twitter/X'
df_twitter = df[mask]
df_twitter.head()

,User_ID,Age,Gender,User_Archetype,Primary_Platform,Daily_Screen_Time_Hours,Dominant_Content_Type,Activity_Type,Late_Night_Usage,Social_Comparison_Trigger,Sleep_Duration_Hours,GAD_7_Score,GAD_7_Severity,PHQ_9_Score,PHQ_9_Severity
0,U-b23639d2,18,Male,Hyper-Connected,Twitter/X,8.50,Gaming,Active,0,0,3.9,9,Mild,5,Mild
7,U-408fc499,18,Female,Hyper-Connected,Twitter/X,7.18,Lifestyle/Fashion,Active,0,0,4.8,6,Mild,5,Mild
10,U-52f7cdb6,18,Female,Hyper-Connected,Twitter/X,7.59,Educational/Tech,Active,1,0,3.3,10,Moderate,17,Moderately Severe
29,U-7dd33870,20,Female,Hyper-Connected,Twitter/X,6.10,News/Politics,Active,1,0,4.4,10,Moderate,7,Mild
69,U-eb7eb16f,18,Male,Digital Minimalist,Twitter/X,1.50,News/Politics,Active,0,0,7.0,0,Minimal,2,None-Minimal

In [ ]:
tw_data = df_twitter.groupby('Age')['Daily_Screen_Time_Hours'].mean()
tw_data

Age
18    4.363414
19    4.202046
20    4.287049
21    4.196226
22    4.654898
Name: Daily_Screen_Time_Hours, dtype: float64

In [ ]:
f'La edad con la que mas se consume Twitter/X es {tw_data.idxmax()} años y el promedio de horas es {round(tw_data.max(), 1)} horas.'

'La edad con la que mas se consume Twitter/X es 22 años y el promedio de horas es 4.7 horas.'

In [ ]:
mask = df['Primary_Platform'] == 'TikTok'
df_tiktok = df[mask]
df_tiktok.head()

,User_ID,Age,Gender,User_Archetype,Primary_Platform,Daily_Screen_Time_Hours,Dominant_Content_Type,Activity_Type,Late_Night_Usage,Social_Comparison_Trigger,Sleep_Duration_Hours,GAD_7_Score,GAD_7_Severity,PHQ_9_Score,PHQ_9_Severity
1,U-e7778765,20,Male,Digital Minimalist,TikTok,0.50,Gaming,Active,0,0,5.5,0,Minimal,8,Mild
38,U-1ae8dde4,20,Female,Average User,TikTok,4.27,Educational/Tech,Active,0,0,5.5,9,Mild,0,None-Minimal
43,U-39fe18d8,18,Female,Average User,TikTok,1.88,Entertainment/Comedy,Active,0,0,8.8,1,Minimal,0,None-Minimal
49,U-a8b4462b,18,Male,Average User,TikTok,2.42,Gaming,Active,0,0,6.4,3,Minimal,2,None-Minimal
57,U-2b1c4ae4,18,Male,Digital Minimalist,TikTok,1.36,Gaming,Active,0,0,5.4,6,Mild,0,None-Minimal

In [ ]:
data_tiktok = df_tiktok.groupby('Age')['Daily_Screen_Time_Hours'].mean()
data_tiktok

Age
18    4.104775
19    4.425470
20    4.322026
21    3.988000
22    4.836563
Name: Daily_Screen_Time_Hours, dtype: float64

In [ ]:
f'La edad en la que mas se consume TikTok es {data_tiktok.idxmax()} años y el promedio de horas diarias es de {round(data_tiktok.max(), 1)} horas.'

'La edad en la que mas se consume TikTok es 22 años y el promedio de horas diarias es de 4.8 horas.'

In [ ]:
mask = df['Primary_Platform'] == 'Snapchat'
df_snapchat = df[mask]
df_snapchat.head()

,User_ID,Age,Gender,User_Archetype,Primary_Platform,Daily_Screen_Time_Hours,Dominant_Content_Type,Activity_Type,Late_Night_Usage,Social_Comparison_Trigger,Sleep_Duration_Hours,GAD_7_Score,GAD_7_Severity,PHQ_9_Score,PHQ_9_Severity
2,U-76749892,18,Female,Digital Minimalist,Snapchat,0.91,Gaming,Active,0,0,8.9,1,Minimal,3,None-Minimal
3,U-dcbbd7f9,18,Female,Hyper-Connected,Snapchat,7.43,Gaming,Active,1,0,6.2,13,Moderate,0,None-Minimal
16,U-b009c953,21,Female,Digital Minimalist,Snapchat,1.67,Educational/Tech,Active,0,0,6.8,6,Mild,0,None-Minimal
18,U-8a4ed12e,21,Male,Average User,Snapchat,3.11,News/Politics,Active,0,0,6.9,9,Mild,0,None-Minimal
25,U-689a3f70,18,Female,Passive Scroller,Snapchat,6.02,Educational/Tech,Passive,1,0,5.7,11,Moderate,1,None-Minimal

In [ ]:
data_snapchat = df_snapchat.groupby('Age')['Daily_Screen_Time_Hours'].mean()
data_snapchat

Age
18    4.305145
19    4.487126
20    4.324215
21    3.659000
22    3.836226
Name: Daily_Screen_Time_Hours, dtype: float64

In [ ]:
f'La edad en la que mas se consume Snapchat es {data_snapchat.idxmax()} años y el uso diario promedio es {round(data_snapchat.max(), 1)} horas.'

'La edad en la que mas se consume Snapchat es 19 años y el uso diario promedio es 4.5 horas.'

In [ ]:
mask = df['Primary_Platform'] == 'LinkedIn'
df_linkedin = df[mask]
df_linkedin.head()

,User_ID,Age,Gender,User_Archetype,Primary_Platform,Daily_Screen_Time_Hours,Dominant_Content_Type,Activity_Type,Late_Night_Usage,Social_Comparison_Trigger,Sleep_Duration_Hours,GAD_7_Score,GAD_7_Severity,PHQ_9_Score,PHQ_9_Severity
4,U-9e1ba278,18,Male,Hyper-Connected,LinkedIn,4.94,Entertainment/Comedy,Active,1,0,5.3,13,Moderate,10,Moderate
9,U-ee0c9c9b,20,Male,Average User,LinkedIn,1.97,Gaming,Active,0,0,4.6,5,Mild,3,None-Minimal
13,U-605ccf37,21,Female,Passive Scroller,LinkedIn,5.17,Gaming,Passive,1,0,5.7,10,Moderate,12,Moderate
17,U-12db71e9,20,Female,Passive Scroller,LinkedIn,6.30,Gaming,Passive,0,0,5.1,12,Moderate,2,None-Minimal
40,U-1d8214eb,18,Male,Hyper-Connected,LinkedIn,9.35,News/Politics,Active,1,0,6.0,12,Moderate,7,Mild

In [ ]:
data_linkedin = df_linkedin.groupby('Age')['Daily_Screen_Time_Hours'].mean()
data_linkedin

Age
18    4.214746
19    4.340536
20    4.170995
21    4.171228
22    4.307692
Name: Daily_Screen_Time_Hours, dtype: float64

In [ ]:
f'La edad en la que mas se utiliza LinkedIn es {data_linkedin.idxmax()} años y el promedio diario de horas de uso es de {round(data_linkedin.max(), 1)} horas.'

'La edad en la que mas se utiliza LinkedIn es 19 años y el promedio diario de horas de uso es de 4.3 horas.'

In [ ]:
mask = df['Primary_Platform'] == 'YouTube'
df_youtube = df[mask]
df_youtube.head()

,User_ID,Age,Gender,User_Archetype,Primary_Platform,Daily_Screen_Time_Hours,Dominant_Content_Type,Activity_Type,Late_Night_Usage,Social_Comparison_Trigger,Sleep_Duration_Hours,GAD_7_Score,GAD_7_Severity,PHQ_9_Score,PHQ_9_Severity
5,U-e578c94a,18,Male,Digital Minimalist,YouTube,0.56,Entertainment/Comedy,Active,0,0,6.2,0,Minimal,2,None-Minimal
12,U-4a6926f5,20,Female,Digital Minimalist,YouTube,1.19,Entertainment/Comedy,Active,0,0,7.0,3,Minimal,1,None-Minimal
14,U-71a32e79,18,Male,Average User,YouTube,3.38,Gaming,Active,0,0,6.0,4,Minimal,1,None-Minimal
15,U-02e9f400,18,Female,Digital Minimalist,YouTube,3.19,Gaming,Active,0,0,8.6,8,Mild,0,None-Minimal
21,U-e51d3cef,20,Male,Hyper-Connected,YouTube,7.38,News/Politics,Active,0,0,3.3,6,Mild,7,Mild

In [ ]:
data_youtube = df_youtube.groupby('Age')['Daily_Screen_Time_Hours'].mean()
data_youtube

Age
18    4.308956
19    4.173740
20    4.199220
21    4.526034
22    3.961500
Name: Daily_Screen_Time_Hours, dtype: float64

In [ ]:
f'La edad en la que mas se consume la plataforma YouTube es {data_youtube.idxmax()} años y el promedio de uso diario es {round(data_youtube.max(), 1)} horas.'

'La edad en la que mas se consume la plataforma YouTube es 21 años y el promedio de uso diario es 4.5 horas.'

In [ ]:
mask = df['Primary_Platform'] == 'Facebook'
df_facebook = df[mask]
df_facebook.head()

,User_ID,Age,Gender,User_Archetype,Primary_Platform,Daily_Screen_Time_Hours,Dominant_Content_Type,Activity_Type,Late_Night_Usage,Social_Comparison_Trigger,Sleep_Duration_Hours,GAD_7_Score,GAD_7_Severity,PHQ_9_Score,PHQ_9_Severity
6,U-a04da6a8,20,Female,Hyper-Connected,Facebook,6.57,Lifestyle/Fashion,Active,1,0,4.7,15,Severe,12,Moderate
8,U-90ce461c,18,Male,Passive Scroller,Facebook,3.41,Lifestyle/Fashion,Passive,0,0,7.0,5,Mild,4,None-Minimal
19,U-1835eda3,19,Male,Average User,Facebook,3.42,Gaming,Active,0,0,6.8,1,Minimal,5,Mild
20,U-e57dec90,19,Male,Hyper-Connected,Facebook,7.96,Gaming,Active,1,0,3.0,9,Mild,12,Moderate
22,U-0a35b86b,20,Male,Hyper-Connected,Facebook,6.88,Self-Help/Motivation,Active,1,0,5.3,10,Moderate,4,None-Minimal

In [ ]:
data_facebook = df_facebook.groupby('Age')['Daily_Screen_Time_Hours'].mean()
data_facebook

Age
18    4.284247
19    4.269598
20    4.476111
21    3.980161
22    4.099687
Name: Daily_Screen_Time_Hours, dtype: float64

In [ ]:
f'La edad con la que mas se consume Facebook es {data_facebook.idxmax()} años y el promedio diario de horas es de {round(data_facebook.max(), 1)} horas.'

'La edad con la que mas se consume Facebook es 20 años y el promedio diario de horas es de 4.5 horas.'

In [ ]:
mask = df['Primary_Platform'] == 'Instagram'
df_instagram = df[mask]
df_instagram.head()

,User_ID,Age,Gender,User_Archetype,Primary_Platform,Daily_Screen_Time_Hours,Dominant_Content_Type,Activity_Type,Late_Night_Usage,Social_Comparison_Trigger,Sleep_Duration_Hours,GAD_7_Score,GAD_7_Severity,PHQ_9_Score,PHQ_9_Severity
11,U-5a564189,20,Female,Average User,Instagram,4.18,Self-Help/Motivation,Active,1,1,5.4,14,Moderate,11,Moderate
27,U-dd5e1f35,20,Male,Digital Minimalist,Instagram,0.80,News/Politics,Active,0,0,7.0,0,Minimal,1,None-Minimal
36,U-7bdd5fe1,18,Female,Digital Minimalist,Instagram,1.15,Self-Help/Motivation,Active,0,1,8.7,4,Minimal,1,None-Minimal
39,U-def4effe,19,Male,Digital Minimalist,Instagram,0.95,Educational/Tech,Active,0,0,6.8,5,Mild,5,Mild
48,U-336e87ee,18,Female,Average User,Instagram,3.76,Educational/Tech,Active,0,0,6.3,0,Minimal,5,Mild

In [ ]:
data_instagram = df_instagram.groupby('Age')['Daily_Screen_Time_Hours'].mean()
data_instagram

Age
18    4.194571
19    4.207281
20    4.281339
21    4.460000
22    5.251224
Name: Daily_Screen_Time_Hours, dtype: float64

In [ ]:
f'La edad en la que mas se consume Instagram es {data_instagram.idxmax()} y el promedio de uso diario es de {round(data_instagram.max(), 1)} horas.'

'La edad en la que mas se consume Instagram es 22 y el promedio de uso diario es de 5.3 horas.'

**¿Cuantas horas consume un usuario al dia de redes sociales?**

In [ ]:
df.head()

,User_ID,Age,Gender,User_Archetype,Primary_Platform,Daily_Screen_Time_Hours,Dominant_Content_Type,Activity_Type,Late_Night_Usage,Social_Comparison_Trigger,Sleep_Duration_Hours,GAD_7_Score,GAD_7_Severity,PHQ_9_Score,PHQ_9_Severity
0,U-b23639d2,18,Male,Hyper-Connected,Twitter/X,8.50,Gaming,Active,0,0,3.9,9,Mild,5,Mild
1,U-e7778765,20,Male,Digital Minimalist,TikTok,0.50,Gaming,Active,0,0,5.5,0,Minimal,8,Mild
2,U-76749892,18,Female,Digital Minimalist,Snapchat,0.91,Gaming,Active,0,0,8.9,1,Minimal,3,None-Minimal
3,U-dcbbd7f9,18,Female,Hyper-Connected,Snapchat,7.43,Gaming,Active,1,0,6.2,13,Moderate,0,None-Minimal
4,U-9e1ba278,18,Male,Hyper-Connected,LinkedIn,4.94,Entertainment/Comedy,Active,1,0,5.3,13,Moderate,10,Moderate

In [ ]:
df.dtypes

User_ID                       object
Age                            int64
Gender                        object
User_Archetype                object
Primary_Platform              object
Daily_Screen_Time_Hours      float64
Dominant_Content_Type         object
Activity_Type                 object
Late_Night_Usage               int64
Social_Comparison_Trigger      int64
Sleep_Duration_Hours         float64
GAD_7_Score                    int64
GAD_7_Severity                object
PHQ_9_Score                    int64
PHQ_9_Severity                object
dtype: object

Cantidad de horas promedio que los usuarios utilizan las redes sociales por dia

In [ ]:
avg_hours_user = df['Daily_Screen_Time_Hours'].mean()
f'Horas promedio de un usuario utilizando redes sociales: {round(avg_hours_user, 2)} horas.'

'Horas promedio de un usuario utilizando redes sociales: 4.28 horas.'

Obtener la cantidad de horas promedio que los usuarios utilizan TikTok

In [ ]:
tiktok_hours = df['Daily_Screen_Time_Hours'][df['Primary_Platform'] == 'TikTok'].mean()
f'Horas promedio que los usuarios destinan al uso de TikTok: {round(tiktok_hours, 2)} horas.'

'Horas promedio que los usuarios destinan al uso de TikTok: 4.28 horas.'

Obtener una tabla con las redes sociales y la cantidad de horas diarias promedio de uso para cada una de ellas

In [ ]:
social_hours = df.groupby('Primary_Platform')['Daily_Screen_Time_Hours'].mean()
round(social_hours, 2)

Primary_Platform
Facebook     4.29
Instagram    4.27
LinkedIn     4.25
Snapchat     4.31
TikTok       4.28
Twitter/X    4.30
YouTube      4.24
Name: Daily_Screen_Time_Hours, dtype: float64