<a href="https://colab.research.google.com/github/mfernandezzz/Pruebas_Tecnicas/blob/main/TT_glassdor_jobs.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df = pd.read_csv('/content/glassdoor_jobs_clean.csv')
pd.set_option('display.max_columns', None)

In [ ]:
df.shape

(956, 15)

In [ ]:
df.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 956 entries, 0 to 955
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0.1       956 non-null    int64
 1   Unnamed: 0         956 non-null    int64
 2   Job Title          956 non-null    object
 3   Salary Estimate    956 non-null    object
 4   Rating             956 non-null    float64
 5   Company Name       956 non-null    object
 6   Location           956 non-null    object
 7   Headquarters       956 non-null    object
 8   Size               956 non-null    object
 9   Founded            956 non-null    int64
 10  Type of ownership  956 non-null    object
 11  Industry           956 non-null    object
 12  Sector             956 non-null    object
 13  Revenue            956 non-null    object
 14  Competitors        956 non-null    object
dtypes: float64(1), int64(3), object(11)
memory usage: 728.3 KB

In [ ]:
#for c in df.select_dtypes('object'):
#  df[c] = df[c].astype('object')

In [ ]:
for i in df.select_dtypes('integer'):
  df[i] = pd.to_numeric(df[i], downcast='integer')

In [ ]:
for f in df.select_dtypes('float'):
  df[f] = pd.to_numeric(df[f], downcast='float')

In [ ]:
df.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 956 entries, 0 to 955
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0.1       956 non-null    int16
 1   Unnamed: 0         956 non-null    int16
 2   Job Title          956 non-null    object
 3   Salary Estimate    956 non-null    object
 4   Rating             956 non-null    float32
 5   Company Name       956 non-null    object
 6   Location           956 non-null    object
 7   Headquarters       956 non-null    object
 8   Size               956 non-null    object
 9   Founded            956 non-null    int16
 10  Type of ownership  956 non-null    object
 11  Industry           956 non-null    object
 12  Sector             956 non-null    object
 13  Revenue            956 non-null    object
 14  Competitors        956 non-null    object
dtypes: float32(1), int16(3), object(11)
memory usage: 707.8 KB

In [ ]:
df.columns = (
    df.columns
    .str.lower()
    .str.strip()
    .str.replace(' ', '_')
)
df.columns

Index(['unnamed:_0.1', 'unnamed:_0', 'job_title', 'salary_estimate', 'rating',
       'company_name', 'location', 'headquarters', 'size', 'founded',
       'type_of_ownership', 'industry', 'sector', 'revenue', 'competitors'],
      dtype='object')

In [ ]:
nulls_count = df.isnull().sum()
nulls_count[nulls_count > 0].sort_values(ascending=False)

Series([], dtype: int64)

In [ ]:
nulls_percentage = df.isnull().mean()*100
nulls_percentage[nulls_percentage > 0].sort_values(ascending=False)

Series([], dtype: float64)

In [ ]:
duplicates_sum = df.duplicated().sum()
duplicates_sum

np.int64(0)

In [ ]:
duplicates_percentage = (df.duplicated().sum()/df.shape[0]) * 100
duplicates_percentage

np.float64(0.0)

In [ ]:
# show_duplicates = df[df.duplicated(keep=False)].sort_values(by=list(df.columns)).head()
# show_duplicates

In [ ]:
# df = df.drop_duplicates()

**¿Cual es el salario promedio anual de un Data Engineer?**

In [ ]:
df.head()

,unnamed:_0.1,unnamed:_0,job_title,salary_estimate,rating,company_name,location,headquarters,size,founded,type_of_ownership,industry,sector,revenue,competitors
0,0,0,Data Scientist,$53K-$91K (Glassdoor est.),3.8,Tecolote Research\n3.8,"Albuquerque, NM","Goleta, CA",501 to 1000 employees,1973,Company - Private,Aerospace & Defense,Aerospace & Defense,$50 to $100 million (USD),-1
1,1,1,Healthcare Data Scientist,$63K-$112K (Glassdoor est.),3.4,University of Maryland Medical System\n3.4,"Linthicum, MD","Baltimore, MD",10000+ employees,1984,Other Organization,Health Care Services & Hospitals,Health Care,$2 to $5 billion (USD),-1
2,2,2,Data Scientist,$80K-$90K (Glassdoor est.),4.8,KnowBe4\n4.8,"Clearwater, FL","Clearwater, FL",501 to 1000 employees,2010,Company - Private,Security Services,Business Services,$100 to $500 million (USD),-1
3,3,3,Data Scientist,$56K-$97K (Glassdoor est.),3.8,PNNL\n3.8,"Richland, WA","Richland, WA",1001 to 5000 employees,1965,Government,Energy,"Oil, Gas, Energy & Utilities",$500 million to $1 billion (USD),"Oak Ridge National Laboratory, National Renewa..."
4,4,4,Data Scientist,$86K-$143K (Glassdoor est.),2.9,Affinity Solutions\n2.9,"New York, NY","New York, NY",51 to 200 employees,1998,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable,"Commerce Signals, Cardlytics, Yodlee"

In [ ]:
df.columns

Index(['unnamed:_0.1', 'unnamed:_0', 'job_title', 'salary_estimate', 'rating',
       'company_name', 'location', 'headquarters', 'size', 'founded',
       'type_of_ownership', 'industry', 'sector', 'revenue', 'competitors'],
      dtype='object')

In [ ]:
df.dtypes

unnamed:_0.1           int16
unnamed:_0             int16
job_title             object
salary_estimate       object
rating               float32
company_name          object
location              object
headquarters          object
size                  object
founded                int16
type_of_ownership     object
industry              object
sector                object
revenue               object
competitors           object
dtype: object

In [ ]:
df['job_title'].value_counts().head()

job_title
Data Scientist           178
Data Engineer             68
Senior Data Scientist     42
Data Analyst              18
Senior Data Engineer      17
Name: count, dtype: int64

In [ ]:
mask = (df['job_title'] == 'Data Engineer') & (df['salary_estimate'] != '-1')
df_data_engineer = df.loc[mask]
df_data_engineer.shape

(53, 15)

In [ ]:
df_data_engineer['salary_estimate'].unique()

array(['$74K-$138K (Glassdoor est.)', '$68K-$129K (Glassdoor est.)',
       '$60K-$114K (Glassdoor est.)', '$68K-$123K (Glassdoor est.)',
       '$54K-$102K (Glassdoor est.)', '$76K-$140K (Glassdoor est.)',
       '$65K-$125K (Glassdoor est.)', '$85K-$159K (Glassdoor est.)',
       '$80K-$105K(Employer est.)',
       'Employer Provided Salary:$120K-$145K',
       '$80K-$120K (Glassdoor est.)', '$59K-$110K (Glassdoor est.)',
       '$48K-$95K (Glassdoor est.)', '$48K-$93K (Glassdoor est.)',
       '$62K-$114K (Glassdoor est.)', '$70K-$132K (Glassdoor est.)',
       '$52K-$99K (Glassdoor est.)', '$67K-$117K (Glassdoor est.)',
       '$65K-$119K (Glassdoor est.)', '$75K-$143K (Glassdoor est.)',
       '$65K-$124K (Glassdoor est.)', '$43K-$86K (Glassdoor est.)',
       '$74K-$124K (Glassdoor est.)', '$76K-$142K (Glassdoor est.)',
       '$61K-$109K (Glassdoor est.)', '$63K-$120K (Glassdoor est.)',
       '$76K-$145K (Glassdoor est.)', '$55K-$105K (Glassdoor est.)',
       '$57K-$80K (Glassdoor est.)', '$79K-$147K (Glassdoor est.)',
       '$42K-$79K (Glassdoor est.)', '$74K-$137K (Glassdoor est.)',
       '$57K-$109K (Glassdoor est.)', '$65K-$126K (Glassdoor est.)',
       '$58K-$104K (Glassdoor est.)', '$62K-$113K (Glassdoor est.)'],
      dtype=object)

In [ ]:
df_data_engineer['salary_estimate'] = (df_data_engineer['salary_estimate']
                                       .astype(str)
                                       .str.strip()
                                       .str.replace('(Glassdoor est.)', '')
                                       .str.replace('(Employer est.)', '')
                                       .str.replace('Employer Provided Salary:', '')
                                       .str.replace('$', '')
                                       .str.replace('K', '000')
                                       .str.replace(' ', ''))
df_data_engineer['salary_estimate'].unique()

/tmp/ipykernel_5365/962683727.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_data_engineer['salary_estimate'] = (df_data_engineer['salary_estimate']

array(['74000-138000', '68000-129000', '60000-114000', '68000-123000',
       '54000-102000', '76000-140000', '65000-125000', '85000-159000',
       '80000-105000', '120000-145000', '80000-120000', '59000-110000',
       '48000-95000', '48000-93000', '62000-114000', '70000-132000',
       '52000-99000', '67000-117000', '65000-119000', '75000-143000',
       '65000-124000', '43000-86000', '74000-124000', '76000-142000',
       '61000-109000', '63000-120000', '76000-145000', '55000-105000',
       '57000-80000', '79000-147000', '42000-79000', '74000-137000',
       '57000-109000', '65000-126000', '58000-104000', '62000-113000'],
      dtype=object)

In [ ]:
data_engineer_salaries = df_data_engineer['salary_estimate'].str.split('-')
data_engineer_salaries.head()

40     [74000, 138000]
43     [68000, 129000]
92     [60000, 114000]
118    [68000, 123000]
125    [54000, 102000]
Name: salary_estimate, dtype: object

In [ ]:
def get_min_max_values(salaries):
  min_values = []
  max_values = []
  for sal in salaries:
    min_values.append(sal[0])
    max_values.append(sal[1])
  return {
      'min_values': min_values,
      'max_values': max_values
  }

data_engineer_salary_ranges = pd.DataFrame(get_min_max_values(data_engineer_salaries))

In [ ]:
data_engineer_salary_ranges.head()

  min_values max_values
0      74000     138000
1      68000     129000
2      60000     114000
3      68000     123000
4      54000     102000

In [ ]:
data_engineer_salary_ranges.dtypes

min_values    object
max_values    object
dtype: object

In [ ]:
data_engineer_salary_ranges['min_values'] = data_engineer_salary_ranges['min_values'].astype(int)
data_engineer_salary_ranges['max_values'] = data_engineer_salary_ranges['max_values'].astype(int)

In [ ]:
data_engineer_salary_ranges.dtypes

min_values    int64
max_values    int64
dtype: object

In [ ]:
data_engineer_salary_ranges['avg'] = ((data_engineer_salary_ranges['min_values']) + (data_engineer_salary_ranges['max_values'])) / 2
data_engineer_salary_ranges.head()

   min_values  max_values       avg
0       74000      138000  106000.0
1       68000      129000   98500.0
2       60000      114000   87000.0
3       68000      123000   95500.0
4       54000      102000   78000.0

In [ ]:
data_engineer_anual_salary = data_engineer_salary_ranges['avg'].sum() / data_engineer_salary_ranges.shape[0]

In [ ]:
f'El salario promedio anual de un Data Engineer es de {round(data_engineer_anual_salary, 2)} dolares.'

'El salario promedio anual de un Data Engineer es de 91660.38 dolares.'

**¿Cual es el salario promedio anual de todas las profesiones que incluyan el termino Data Engineer?**

In [ ]:
mask = (df['job_title'].str.contains('Data Engineer')) & (df['salary_estimate'] != '-1')
all_data_engineer = df.loc[mask]
all_data_engineer['job_title'].unique()

array(['Data Engineer I', 'Data Engineer', 'Senior Data Engineer',
       'Data Engineer 4 - Contract', 'MongoDB Data Engineer II',
       'Data Engineer 5 - Contract (Remote)', 'Lead Data Engineer',
       'Sr. Data Engineer - Contract-to-Hire (Java)', 'Sr. Data Engineer',
       'Big Data Engineer - Chicago - Future Opportunity',
       'SQL Data Engineer', 'Data Engineer I - Azure',
       'Data Engineer, Data Engineering and Artifical Intelligence',
       'Principal Data Engineer, Data Platform & Insights',
       'Big Data Engineer', 'Staff Data Engineer',
       'Associate Data Engineer', 'Staff BI and Data Engineer',
       'Associate Director, Platform and DevOps- Data Engineering and Aritifical Intelligence',
       'IT - Data Engineer II', 'Sr Data Engineer (Sr BI Developer)',
       'Lead Big Data Engineer', 'Sr. Data Engineer (ETL Developer)',
       'Lead Data Engineer (Python)', 'Software Data Engineer - College',
       'Data Engineer - Consultant (Charlotte Based)',
       'Data Engineer - ETL', 'Data Engineering Analyst',
       'Sr. Data Engineer | Big Data SaaS Pipeline'], dtype=object)

In [ ]:
all_data_engineer.shape

(119, 15)

In [ ]:
mask_invalid = (df['job_title'].str.contains('Data Engineer')) & (df['salary_estimate'] == '-1')
invalid_records = df.loc[mask_invalid]
invalid_records.head()

,unnamed:_0.1,unnamed:_0,job_title,salary_estimate,rating,company_name,location,headquarters,size,founded,type_of_ownership,industry,sector,revenue,competitors
53,53,53,Data Engineer,-1,4.5,Anson McCade\n4.5,"Kingdom, IL","London, United Kingdom",51 to 200 employees,2000,Company - Private,Staffing & Outsourcing,Business Services,$1 to $5 million (USD),-1
100,100,100,Data Engineer Intern,-1,4.7,ThousandEyes\n4.7,"San Francisco, CA","San Francisco, CA",201 to 500 employees,2010,Company - Private,Computer Hardware & Software,Information Technology,Unknown / Non-Applicable,-1
115,115,115,Data Engineer,-1,4.5,NuWave Solutions\n4.5,Virginia,"Mc Lean, VA",51 to 200 employees,1999,Company - Private,IT Services,Information Technology,$5 to $10 million (USD),-1
163,163,163,Data Engineer,-1,4.0,Hygiena\n4.0,"Camarillo, CA","Camarillo, CA",201 to 500 employees,-1,Company - Private,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$100 to $500 million (USD),"Ecolab, Eurofin Private Investment Office"
220,220,220,AWS Data Engineer,-1,4.5,NuWave Solutions\n4.5,Virginia,"Mc Lean, VA",51 to 200 employees,1999,Company - Private,IT Services,Information Technology,$5 to $10 million (USD),-1

In [ ]:
invalid_records.shape

(39, 15)

In [ ]:
all_data_engineer['salary_estimate'].unique()

array(['$102K-$190K (Glassdoor est.)', '$74K-$138K (Glassdoor est.)',
       '$68K-$129K (Glassdoor est.)', '$60K-$114K (Glassdoor est.)',
       '$68K-$123K (Glassdoor est.)', '$54K-$102K (Glassdoor est.)',
       '$76K-$140K (Glassdoor est.)', '$65K-$125K (Glassdoor est.)',
       '$95K-$173K (Glassdoor est.)', '$85K-$159K (Glassdoor est.)',
       '$80K-$105K(Employer est.)',
       'Employer Provided Salary:$120K-$145K',
       '$80K-$120K (Glassdoor est.)', '$59K-$115K (Glassdoor est.)',
       '$77K-$136K (Glassdoor est.)', '$59K-$110K (Glassdoor est.)',
       '$74K-$140K (Glassdoor est.)', '$48K-$95K (Glassdoor est.)',
       '$48K-$93K (Glassdoor est.)', '$190K-$220K(Employer est.)',
       '$69K-$127K (Glassdoor est.)', '$75K-$140K (Glassdoor est.)',
       '$62K-$114K (Glassdoor est.)', '$71K-$129K (Glassdoor est.)',
       '$67K-$119K (Glassdoor est.)', '$70K-$132K (Glassdoor est.)',
       '$54K-$101K (Glassdoor est.)', '$52K-$99K (Glassdoor est.)',
       '$71K-$134K (Glassdoor est.)', '$67K-$117K (Glassdoor est.)',
       '$116K-$209K (Glassdoor est.)', '$62K-$119K (Glassdoor est.)',
       '$65K-$119K (Glassdoor est.)', '$75K-$143K (Glassdoor est.)',
       '$105K-$194K (Glassdoor est.)', '$45K-$86K (Glassdoor est.)',
       '$80K-$148K (Glassdoor est.)', '$65K-$124K (Glassdoor est.)',
       '$43K-$86K (Glassdoor est.)', '$113K-$196K (Glassdoor est.)',
       '$74K-$124K (Glassdoor est.)', '$76K-$142K (Glassdoor est.)',
       '$87K-$158K (Glassdoor est.)', '$61K-$119K (Glassdoor est.)',
       '$78K-$147K (Glassdoor est.)', '$90K-$110K(Employer est.)',
       '$61K-$109K (Glassdoor est.)', '$97K-$180K (Glassdoor est.)',
       '$121K-$203K (Glassdoor est.)', '$83K-$148K (Glassdoor est.)',
       '$66K-$123K (Glassdoor est.)', '$97K-$181K (Glassdoor est.)',
       '$100K-$173K (Glassdoor est.)', '$63K-$120K (Glassdoor est.)',
       '$126K-$228K (Glassdoor est.)', '$76K-$145K (Glassdoor est.)',
       '$49K-$97K (Glassdoor est.)', '$55K-$105K (Glassdoor est.)',
       '$57K-$80K (Glassdoor est.)', '$59K-$112K (Glassdoor est.)',
       '$79K-$147K (Glassdoor est.)', '$72K-$133K (Glassdoor est.)',
       '$44K-$86K (Glassdoor est.)', '$67K-$127K (Glassdoor est.)',
       '$42K-$79K (Glassdoor est.)', '$84K-$153K (Glassdoor est.)',
       '$44K-$73K (Glassdoor est.)', '$74K-$137K (Glassdoor est.)',
       '$57K-$109K (Glassdoor est.)', '$65K-$126K (Glassdoor est.)',
       '$58K-$104K (Glassdoor est.)', '$71K-$135K (Glassdoor est.)',
       '$62K-$113K (Glassdoor est.)'], dtype=object)

In [ ]:
all_data_engineer['salary_estimate'] = (all_data_engineer['salary_estimate']
                                        .astype(str)
                                        .str.strip()
                                        .str.replace('(Glassdoor est.)', '')
                                        .str.replace('(Employer est.)', '')
                                        .str.replace('Employer Provided Salary:', '')
                                        .str.replace('$', '')
                                        .str.replace('K', '000')
                                        .str.replace(' ', ''))
all_data_engineer['salary_estimate'].unique()

/tmp/ipykernel_5365/2000599922.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  all_data_engineer['salary_estimate'] = (all_data_engineer['salary_estimate']

array(['102000-190000', '74000-138000', '68000-129000', '60000-114000',
       '68000-123000', '54000-102000', '76000-140000', '65000-125000',
       '95000-173000', '85000-159000', '80000-105000', '120000-145000',
       '80000-120000', '59000-115000', '77000-136000', '59000-110000',
       '74000-140000', '48000-95000', '48000-93000', '190000-220000',
       '69000-127000', '75000-140000', '62000-114000', '71000-129000',
       '67000-119000', '70000-132000', '54000-101000', '52000-99000',
       '71000-134000', '67000-117000', '116000-209000', '62000-119000',
       '65000-119000', '75000-143000', '105000-194000', '45000-86000',
       '80000-148000', '65000-124000', '43000-86000', '113000-196000',
       '74000-124000', '76000-142000', '87000-158000', '61000-119000',
       '78000-147000', '90000-110000', '61000-109000', '97000-180000',
       '121000-203000', '83000-148000', '66000-123000', '97000-181000',
       '100000-173000', '63000-120000', '126000-228000', '76000-145000',
       '49000-97000', '55000-105000', '57000-80000', '59000-112000',
       '79000-147000', '72000-133000', '44000-86000', '67000-127000',
       '42000-79000', '84000-153000', '44000-73000', '74000-137000',
       '57000-109000', '65000-126000', '58000-104000', '71000-135000',
       '62000-113000'], dtype=object)

In [ ]:
all_data_engineer_salaries = all_data_engineer['salary_estimate'].str.split('-')
all_data_engineer_salaries_ranges = pd.DataFrame(get_min_max_values(all_data_engineer_salaries))
all_data_engineer_salaries_ranges.head()

  min_values max_values
0     102000     190000
1      74000     138000
2      68000     129000
3      60000     114000
4      68000     123000

In [ ]:
all_data_engineer_salaries_ranges['min_values'] = all_data_engineer_salaries_ranges['min_values'].astype(int)
all_data_engineer_salaries_ranges['max_values'] = all_data_engineer_salaries_ranges['max_values'].astype(int)

In [ ]:
all_data_engineer_salaries_ranges['avg'] = (all_data_engineer_salaries_ranges['min_values'] + all_data_engineer_salaries_ranges['max_values']) / 2
all_data_engineer_salaries_ranges.head()

   min_values  max_values       avg
0      102000      190000  146000.0
1       74000      138000  106000.0
2       68000      129000   98500.0
3       60000      114000   87000.0
4       68000      123000   95500.0

In [ ]:
all_data_engineer_avg_salary = all_data_engineer_salaries_ranges['avg'].sum() / all_data_engineer_salaries_ranges.shape[0]

In [ ]:
f'El salario promedio anual para todas las profesiones de Data Engineer es de {round(all_data_engineer_avg_salary, 2)} dolares.'

'El salario promedio anual para todas las profesiones de Data Engineer es de 105403.36 dolares.'

**¿Cuales son los cinco trabajos mas demandados de USA?**

In [ ]:
df['job_title'].value_counts(normalize=True).head()

job_title
Data Scientist           0.186192
Data Engineer            0.071130
Senior Data Scientist    0.043933
Data Analyst             0.018828
Senior Data Engineer     0.017782
Name: proportion, dtype: float64

In [ ]:
popular_jobs = pd.DataFrame(df['job_title'].value_counts()).reset_index()
popular_jobs.rename(columns={'count': 'total_offers'}, inplace=True)
popular_jobs['%'] = round((popular_jobs['total_offers'] / popular_jobs['total_offers'].sum()) * 100, 2)
popular_jobs.head()

               job_title  total_offers      %
0         Data Scientist           178  18.62
1          Data Engineer            68   7.11
2  Senior Data Scientist            42   4.39
3           Data Analyst            18   1.88
4   Senior Data Engineer            17   1.78

In [ ]:
top5_jobs = (df['job_title'].value_counts(normalize=True)*100).round(2).reset_index()
top5_jobs.rename(columns={'proportion': '%'}, inplace=True)
top5_jobs.head()

               job_title      %
0         Data Scientist  18.62
1          Data Engineer   7.11
2  Senior Data Scientist   4.39
3           Data Analyst   1.88
4   Senior Data Engineer   1.78

**¿Cual es el salario promedio de todas las profesiones de Data Analyst?**

In [ ]:
mask_da = (df['job_title'].str.contains('Data Analyst')) & (df['salary_estimate'] != '-1')
all_data_analyst = df.loc[mask_da]
all_data_analyst.shape

(99, 15)

In [ ]:
all_data_analyst['salary_estimate'].unique()

array(['$46K-$85K (Glassdoor est.)', '$34K-$61K (Glassdoor est.)',
       '$77K-$135K (Glassdoor est.)', '$64K-$112K (Glassdoor est.)',
       '$20K-$39K (Glassdoor est.)', '$37K-$76K (Glassdoor est.)',
       '$55K-$100K (Glassdoor est.)', '$39K-$68K (Glassdoor est.)',
       '$34K-$62K (Glassdoor est.)', '$52K-$93K (Glassdoor est.)',
       '$40K-$73K (Glassdoor est.)', '$41K-$72K (Glassdoor est.)',
       '$39K-$71K (Glassdoor est.)', '$43K-$81K (Glassdoor est.)',
       '$71K-$136K (Glassdoor est.)', '$44K-$78K (Glassdoor est.)',
       '$43K-$80K (Glassdoor est.)', '$31K-$72K (Glassdoor est.)',
       '$42K-$76K (Glassdoor est.)', '$35K-$62K (Glassdoor est.)',
       '$44K-$86K (Glassdoor est.)', '$65K-$120K (Glassdoor est.)',
       '$33K-$62K (Glassdoor est.)', '$48K-$90K (Glassdoor est.)',
       '$34K-$64K (Glassdoor est.)', '$55K-$97K (Glassdoor est.)',
       '$74K-$126K (Glassdoor est.)', '$37K-$63K (Glassdoor est.)',
       '$45K-$82K (Glassdoor est.)', '$42K-$74K (Glassdoor est.)',
       '$60K-$102K (Glassdoor est.)', '$55K-$99K (Glassdoor est.)',
       '$52K-$89K (Glassdoor est.)', '$31K-$57K (Glassdoor est.)',
       '$36K-$62K (Glassdoor est.)', '$50K-$92K (Glassdoor est.)',
       '$42K-$80K (Glassdoor est.)', '$32K-$59K (Glassdoor est.)',
       '$43K-$77K (Glassdoor est.)', '$65K-$110K (Glassdoor est.)',
       '$31K-$55K (Glassdoor est.)', '$48K-$85K (Glassdoor est.)',
       '$10-$17 Per Hour(Glassdoor est.)', '$49K-$76K (Glassdoor est.)',
       '$54K-$92K (Glassdoor est.)', '$42K-$77K (Glassdoor est.)',
       '$47K-$85K (Glassdoor est.)', '$35K-$65K (Glassdoor est.)',
       '$90K-$157K (Glassdoor est.)', '$32K-$62K (Glassdoor est.)',
       '$39K-$69K (Glassdoor est.)', '$27K-$48K (Glassdoor est.)',
       '$36K-$71K (Glassdoor est.)', '$99K-$178K (Glassdoor est.)',
       '$53K-$91K (Glassdoor est.)', '$33K-$61K (Glassdoor est.)',
       '$69K-$119K (Glassdoor est.)', '$90K-$153K (Glassdoor est.)',
       '$58K-$108K (Glassdoor est.)', '$61K-$110K (Glassdoor est.)',
       '$32K-$57K (Glassdoor est.)', '$79K-$136K (Glassdoor est.)',
       '$50K-$89K (Glassdoor est.)'], dtype=object)

In [ ]:
all_data_analyst.loc[all_data_analyst['salary_estimate'] == '$10-$17 Per Hour(Glassdoor est.)']

,unnamed:_0.1,unnamed:_0,job_title,salary_estimate,rating,company_name,location,headquarters,size,founded,type_of_ownership,industry,sector,revenue,competitors
523,523,523,"Senior Operations Data Analyst, Call Center Op...",$10-$17 Per Hour(Glassdoor est.),2.7,FLEETCOR\n2.7,"Nashville, TN","Peachtree Corners, GA",5001 to 10000 employees,2000,Company - Public,Financial Transaction Processing,Finance,$2 to $5 billion (USD),-1
787,787,787,"Senior Operations Data Analyst, Call Center Op...",$10-$17 Per Hour(Glassdoor est.),2.7,FLEETCOR\n2.7,"Nashville, TN","Peachtree Corners, GA",5001 to 10000 employees,2000,Company - Public,Financial Transaction Processing,Finance,$2 to $5 billion (USD),-1

In [ ]:
all_data_analyst = all_data_analyst[~(all_data_analyst['salary_estimate'] == '$10-$17 Per Hour(Glassdoor est.)')]

In [ ]:
all_data_analyst['salary_estimate'] = (all_data_analyst['salary_estimate']
                                       .astype(str)
                                       .str.strip()
                                       .str.replace('(Glassdoor est.)', '')
                                       .str.replace('(Employer est.)', '')
                                       .str.replace('Employer Provided Salary:', '')
                                       .str.replace('$', '')
                                       .str.replace('K', '000')
                                       .str.replace(' ', '')
                                       .str.replace('PerHour', ''))
all_data_analyst['salary_estimate'].unique()

/tmp/ipykernel_5365/3654073807.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  all_data_analyst['salary_estimate'] = (all_data_analyst['salary_estimate']

array(['46000-85000', '34000-61000', '77000-135000', '64000-112000',
       '20000-39000', '37000-76000', '55000-100000', '39000-68000',
       '34000-62000', '52000-93000', '40000-73000', '41000-72000',
       '39000-71000', '43000-81000', '71000-136000', '44000-78000',
       '43000-80000', '31000-72000', '42000-76000', '35000-62000',
       '44000-86000', '65000-120000', '33000-62000', '48000-90000',
       '34000-64000', '55000-97000', '74000-126000', '37000-63000',
       '45000-82000', '42000-74000', '60000-102000', '55000-99000',
       '52000-89000', '31000-57000', '36000-62000', '50000-92000',
       '42000-80000', '32000-59000', '43000-77000', '65000-110000',
       '31000-55000', '48000-85000', '49000-76000', '54000-92000',
       '42000-77000', '47000-85000', '35000-65000', '90000-157000',
       '32000-62000', '39000-69000', '27000-48000', '36000-71000',
       '99000-178000', '53000-91000', '33000-61000', '69000-119000',
       '90000-153000', '58000-108000', '61000-110000', '32000-57000',
       '79000-136000', '50000-89000'], dtype=object)

In [ ]:
all_data_analyst_salary = all_data_analyst['salary_estimate'].str.split('-')
all_data_analyst_salary_ranges = pd.DataFrame(get_min_max_values(all_data_analyst_salary))
all_data_analyst_salary_ranges.head()

  min_values max_values
0      46000      85000
1      34000      61000
2      77000     135000
3      64000     112000
4      20000      39000

In [ ]:
all_data_analyst_salary_ranges.dtypes

min_values    object
max_values    object
dtype: object

In [ ]:
all_data_analyst_salary_ranges['min_values'] = all_data_analyst_salary_ranges['min_values'].astype(int)
all_data_analyst_salary_ranges['max_values'] = all_data_analyst_salary_ranges['max_values'].astype(int)
all_data_analyst_salary_ranges.dtypes

min_values    int64
max_values    int64
dtype: object

In [ ]:
all_data_analyst_salary_ranges['avg'] = (all_data_analyst_salary_ranges['min_values'] + all_data_analyst_salary_ranges['max_values']) / 2
all_data_analyst_salary_ranges.head()

   min_values  max_values       avg
0       46000       85000   65500.0
1       34000       61000   47500.0
2       77000      135000  106000.0
3       64000      112000   88000.0
4       20000       39000   29500.0

In [ ]:
all_data_analyst_avg_salary = all_data_analyst_salary_ranges['avg'].sum() / all_data_analyst_salary_ranges.shape[0]
f'El salario promedio para todas las profesiones de Analista de Datos es de {round(all_data_analyst_avg_salary, 2)} dolares.'

'El salario promedio para todas las profesiones de Analista de Datos es de 65675.26 dolares.'