<a href="https://colab.research.google.com/github/mfernandezzz/Pruebas_Tecnicas/blob/main/TT_lol.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df = pd.read_csv('/content/lol_data.csv')
pd.set_option('display.max_columns', None)

In [ ]:
df.shape

(172, 33)

In [ ]:
df.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 172 entries, 0 to 171
Data columns (total 33 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Unnamed: 0          172 non-null    object
 1   id                  172 non-null    float64
 2   apiname             172 non-null    object
 3   title               172 non-null    object
 4   difficulty          172 non-null    int64
 5   herotype            172 non-null    object
 6   alttype             144 non-null    object
 7   resource            167 non-null    object
 8   stats               172 non-null    object
 9   rangetype           172 non-null    object
 10  date                172 non-null    object
 11  patch               172 non-null    object
 12  changes             172 non-null    object
 13  role                172 non-null    object
 14  client_positions    172 non-null    object
 15  external_positions  172 non-null    object
 16  damage              172 non-null    int64
 17  toughness           172 non-null    int64
 18  control             172 non-null    int64
 19  mobility            172 non-null    int64
 20  utility             172 non-null    int64
 21  style               172 non-null    int64
 22  adaptivetype        172 non-null    object
 23  be                  172 non-null    int64
 24  rp                  172 non-null    int64
 25  skill_i             172 non-null    object
 26  skill_q             172 non-null    object
 27  skill_w             172 non-null    object
 28  skill_e             172 non-null    object
 29  skill_r             172 non-null    object
 30  skills              170 non-null    object
 31  fullname            43 non-null     object
 32  nickname            14 non-null     object
dtypes: float64(1), int64(9), object(23)
memory usage: 354.6 KB

In [ ]:
#for c in df.select_dtypes('object'):
#  df[c] = df[c].astype('category')

In [ ]:
for i in df.select_dtypes('integer'):
  df[i] = pd.to_numeric(df[i], downcast='integer')

In [ ]:
for f in df.select_dtypes('float'):
  df[f] = pd.to_numeric(df[f], downcast='float')

In [ ]:
df.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 172 entries, 0 to 171
Data columns (total 33 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Unnamed: 0          172 non-null    object
 1   id                  172 non-null    float32
 2   apiname             172 non-null    object
 3   title               172 non-null    object
 4   difficulty          172 non-null    int8
 5   herotype            172 non-null    object
 6   alttype             144 non-null    object
 7   resource            167 non-null    object
 8   stats               172 non-null    object
 9   rangetype           172 non-null    object
 10  date                172 non-null    object
 11  patch               172 non-null    object
 12  changes             172 non-null    object
 13  role                172 non-null    object
 14  client_positions    172 non-null    object
 15  external_positions  172 non-null    object
 16  damage              172 non-null    int8
 17  toughness           172 non-null    int8
 18  control             172 non-null    int8
 19  mobility            172 non-null    int8
 20  utility             172 non-null    int8
 21  style               172 non-null    int8
 22  adaptivetype        172 non-null    object
 23  be                  172 non-null    int16
 24  rp                  172 non-null    int16
 25  skill_i             172 non-null    object
 26  skill_q             172 non-null    object
 27  skill_w             172 non-null    object
 28  skill_e             172 non-null    object
 29  skill_r             172 non-null    object
 30  skills              170 non-null    object
 31  fullname            43 non-null     object
 32  nickname            14 non-null     object
dtypes: float32(1), int16(2), int8(7), object(23)
memory usage: 343.7 KB

In [ ]:
df.columns = (
    df.columns
    .str.lower()
    .str.strip()
    .str.replace(' ', '_')
)
df.columns

Index(['unnamed:_0', 'id', 'apiname', 'title', 'difficulty', 'herotype',
       'alttype', 'resource', 'stats', 'rangetype', 'date', 'patch', 'changes',
       'role', 'client_positions', 'external_positions', 'damage', 'toughness',
       'control', 'mobility', 'utility', 'style', 'adaptivetype', 'be', 'rp',
       'skill_i', 'skill_q', 'skill_w', 'skill_e', 'skill_r', 'skills',
       'fullname', 'nickname'],
      dtype='object')

In [ ]:
nulls_count = df.isnull().sum()
nulls_count[nulls_count > 0].sort_values(ascending=False)

Series([], dtype: int64)

In [ ]:
nulls_percentage = df.isnull().mean()*100
nulls_percentage[nulls_percentage > 0].sort_values(ascending=False)

Series([], dtype: float64)

In [ ]:
duplicates_sum = df.duplicated().sum()
duplicates_sum

np.int64(0)

In [ ]:
duplicates_percentage = (df.duplicated().sum()/df.shape[0]) * 100
duplicates_percentage

np.float64(0.0)

In [ ]:
# show_duplicates = df[df.duplicated(keep=False)].sort_values(by=list(df.columns)).head()
# show_duplicates

In [ ]:
# df = df.drop_duplicates()

In [ ]:
df.head()

,unnamed:_0,id,apiname,title,difficulty,herotype,alttype,resource,stats,rangetype,date,patch,changes,role,client_positions,external_positions,damage,toughness,control,mobility,utility,style,adaptivetype,be,rp,skill_i,skill_q,skill_w,skill_e,skill_r,skills,fullname,nickname
0,Aatrox,266.0,Aatrox,the Darkin Blade,2,Fighter,Tank,Blood Well,"{'hp_base': 650, 'hp_lvl': 114, 'mp_base': 0, ...",Melee,2013-06-13,V3.8,V14.23,{'Juggernaut'},{'Top'},{'Top'},3,3,2,2,2,20,Physical,4800,880,{1: 'Deathbringer Stance'},"{1: 'The Darkin Blade', 2: 'The Darkin Blade 3'}",{1: 'Infernal Chains'},{1: 'Umbral Dash'},{1: 'World Ender'},"{1: 'Deathbringer Stance', 2: 'The Darkin Blad...",NaN,NaN
1,Ahri,103.0,Ahri,the Nine-Tailed Fox,2,Mage,Assassin,Mana,"{'hp_base': 590, 'hp_lvl': 104, 'mp_base': 418...",Ranged,2011-12-14,V1.0.0.131,V14.18,{'Burst'},{'Middle'},{'Middle'},3,1,2,3,1,100,Magic,3150,790,{1: 'Essence Theft'},{1: 'Orb of Deception'},{1: 'Fox-Fire'},{1: 'Charm'},{1: 'Spirit Rush'},"{1: 'Essence Theft', 2: 'Orb of Deception', 3:...",NaN,NaN
2,Akali,84.0,Akali,the Rogue Assassin,2,Assassin,NaN,Energy,"{'hp_base': 600, 'hp_lvl': 119, 'mp_base': 200...",Melee,2010-05-11,V1.0.0.85,V14.18,{'Assassin'},"{'Middle', 'Top'}","{'Middle', 'Top'}",3,1,1,3,1,65,Physical,3150,790,"{1: ""Assassin's Mark""}",{1: 'Five Point Strike'},{1: 'Twilight Shroud'},{1: 'Shuriken Flip'},{1: 'Perfect Execution'},"{1: ""Assassin's Mark"", 2: 'Five Point Strike',...",Akali Jhomen Tethi,NaN
3,Akshan,166.0,Akshan,the Rogue Sentinel,3,Marksman,Assassin,Mana,"{'hp_base': 630, 'hp_lvl': 107, 'mp_base': 350...",Ranged,2021-07-22,V11.15,V14.22,"{'Assassin', 'Marksman'}",{'Middle'},{'Middle'},3,1,1,3,2,1,Physical,4800,880,{1: 'Dirty Fighting'},{1: 'Avengerang'},{1: 'Going Rogue'},{1: 'Heroic Swing'},{1: 'Comeuppance'},"{1: 'Dirty Fighting', 2: 'Avengerang', 3: 'Goi...",NaN,NaN
4,Alistar,12.0,Alistar,the Minotaur,1,Tank,Support,Mana,"{'hp_base': 685, 'hp_lvl': 120, 'mp_base': 350...",Melee,2009-02-21,Alpha Week 2,V14.16,{'Vanguard'},{'Support'},{'Support'},1,3,3,1,2,65,Magic,1350,585,{1: 'Triumphant Roar'},{1: 'Pulverize'},{1: 'Headbutt'},{1: 'Trample'},{1: 'Unbreakable Will'},"{1: 'Triumphant Roar', 2: 'Pulverize', 3: 'Hea...",NaN,NaN

In [ ]:
df['nickname'].unique()

array([nan, 'GP', 'J4', 'Rhaast, Darkin, Shadow Assassin',
       'Rainbow Scyther', 'LB', 'Cute jungler', 'MF',
       'Darkrider, DarkSupport', 'Renata', 'TF', 'Darkin, Valmar, Kai',
       '6', 'Zaun Amorphous Combatant, Z.A.C.', 'Kagetora'], dtype=object)

In [ ]:
df['unnamed:_0'].nunique()

172

In [ ]:
df.drop(columns='nickname', inplace=True)

In [ ]:
df.columns

Index(['unnamed:_0', 'id', 'apiname', 'title', 'difficulty', 'herotype',
       'alttype', 'resource', 'stats', 'rangetype', 'date', 'patch', 'changes',
       'role', 'client_positions', 'external_positions', 'damage', 'toughness',
       'control', 'mobility', 'utility', 'style', 'adaptivetype', 'be', 'rp',
       'skill_i', 'skill_q', 'skill_w', 'skill_e', 'skill_r', 'skills',
       'fullname'],
      dtype='object')

In [ ]:
df.rename(columns={'unnamed:_0': 'nickname'}, inplace=True)

In [ ]:
df.head()

,nickname,id,apiname,title,difficulty,herotype,alttype,resource,stats,rangetype,date,patch,changes,role,client_positions,external_positions,damage,toughness,control,mobility,utility,style,adaptivetype,be,rp,skill_i,skill_q,skill_w,skill_e,skill_r,skills,fullname
0,Aatrox,266.0,Aatrox,the Darkin Blade,2,Fighter,Tank,Blood Well,"{'hp_base': 650, 'hp_lvl': 114, 'mp_base': 0, ...",Melee,2013-06-13,V3.8,V14.23,{'Juggernaut'},{'Top'},{'Top'},3,3,2,2,2,20,Physical,4800,880,{1: 'Deathbringer Stance'},"{1: 'The Darkin Blade', 2: 'The Darkin Blade 3'}",{1: 'Infernal Chains'},{1: 'Umbral Dash'},{1: 'World Ender'},"{1: 'Deathbringer Stance', 2: 'The Darkin Blad...",NaN
1,Ahri,103.0,Ahri,the Nine-Tailed Fox,2,Mage,Assassin,Mana,"{'hp_base': 590, 'hp_lvl': 104, 'mp_base': 418...",Ranged,2011-12-14,V1.0.0.131,V14.18,{'Burst'},{'Middle'},{'Middle'},3,1,2,3,1,100,Magic,3150,790,{1: 'Essence Theft'},{1: 'Orb of Deception'},{1: 'Fox-Fire'},{1: 'Charm'},{1: 'Spirit Rush'},"{1: 'Essence Theft', 2: 'Orb of Deception', 3:...",NaN
2,Akali,84.0,Akali,the Rogue Assassin,2,Assassin,NaN,Energy,"{'hp_base': 600, 'hp_lvl': 119, 'mp_base': 200...",Melee,2010-05-11,V1.0.0.85,V14.18,{'Assassin'},"{'Middle', 'Top'}","{'Middle', 'Top'}",3,1,1,3,1,65,Physical,3150,790,"{1: ""Assassin's Mark""}",{1: 'Five Point Strike'},{1: 'Twilight Shroud'},{1: 'Shuriken Flip'},{1: 'Perfect Execution'},"{1: ""Assassin's Mark"", 2: 'Five Point Strike',...",Akali Jhomen Tethi
3,Akshan,166.0,Akshan,the Rogue Sentinel,3,Marksman,Assassin,Mana,"{'hp_base': 630, 'hp_lvl': 107, 'mp_base': 350...",Ranged,2021-07-22,V11.15,V14.22,"{'Assassin', 'Marksman'}",{'Middle'},{'Middle'},3,1,1,3,2,1,Physical,4800,880,{1: 'Dirty Fighting'},{1: 'Avengerang'},{1: 'Going Rogue'},{1: 'Heroic Swing'},{1: 'Comeuppance'},"{1: 'Dirty Fighting', 2: 'Avengerang', 3: 'Goi...",NaN
4,Alistar,12.0,Alistar,the Minotaur,1,Tank,Support,Mana,"{'hp_base': 685, 'hp_lvl': 120, 'mp_base': 350...",Melee,2009-02-21,Alpha Week 2,V14.16,{'Vanguard'},{'Support'},{'Support'},1,3,3,1,2,65,Magic,1350,585,{1: 'Triumphant Roar'},{1: 'Pulverize'},{1: 'Headbutt'},{1: 'Trample'},{1: 'Unbreakable Will'},"{1: 'Triumphant Roar', 2: 'Pulverize', 3: 'Hea...",NaN

In [ ]:
cat_cols = ['fullname', 'skills']
df[cat_cols] = df[cat_cols].fillna('Unknown')

In [ ]:
df['resource'].unique()

array(['Blood Well', 'Mana', 'Energy', nan, 'Frenzy', 'Health', 'Rage',
       'Courage', 'Shield', 'Fury', 'Ferocity', 'Heat', 'Grit',
       'Crimson Rush', 'Flow'], dtype=object)

In [ ]:
df['resource'] = df['resource'].fillna('Unknown')
resource_unk = df.loc[df['resource'] == 'Unknown']
resource_unk

,nickname,id,apiname,title,difficulty,herotype,alttype,resource,stats,rangetype,date,patch,changes,role,client_positions,external_positions,damage,toughness,control,mobility,utility,style,adaptivetype,be,rp,skill_i,skill_q,skill_w,skill_e,skill_r,skills,fullname
15,Bel'Veth,200.0,Belveth,the Empress of the Void,2,Fighter,NaN,Unknown,"{'hp_base': 610, 'hp_lvl': 99, 'mp_base': 0, '...",Melee,2022-06-09,V12.11,V14.18,{'Skirmisher'},{'Jungle'},{'Jungle'},3,1,2,3,1,0,Physical,3150,790,{1: 'Death in Lavender'},{1: 'Void Surge'},{1: 'Above and Below'},{1: 'Royal Maelstrom'},{1: 'Endless Banquet'},"{1: 'Death in Lavender', 2: 'Void Surge', 3: '...",Unknown
38,Garen,86.0,Garen,The Might of Demacia,1,Fighter,Tank,Unknown,"{'hp_base': 690, 'hp_lvl': 98, 'mp_base': 0, '...",Melee,2010-04-27,V1.0.0.83,V14.9,{'Juggernaut'},{'Top'},{'Top'},2,3,1,1,1,75,Physical,450,260,{1: 'Perseverance'},{1: 'Decisive Strike'},{1: 'Courage'},"{1: 'Judgment', 2: 'Judgment 2'}",{1: 'Demacian Justice'},"{1: 'Perseverance', 2: 'Decisive Strike', 3: '...",Garen Crownguard
62,Katarina,55.0,Katarina,the Sinister Blade,2,Assassin,Mage,Unknown,"{'hp_base': 672, 'hp_lvl': 108, 'mp_base': 0, ...",Melee,2009-09-19,V0.9.25.21,V14.22,{'Assassin'},{'Middle'},{'Middle'},3,1,1,3,1,100,Magic,3150,790,"{1: 'Voracity', 2: 'Sinister Steel'}",{1: 'Bouncing Blade'},{1: 'Preparation'},{1: 'Shunpo'},{1: 'Death Lotus'},"{1: 'Voracity', 2: 'Sinister Steel', 3: 'Bounc...",Katarina Du Couteau
112,Riven,92.0,Riven,the Exile,2,Fighter,Assassin,Unknown,"{'hp_base': 630, 'hp_lvl': 100, 'mp_base': 0, ...",Melee,2011-09-14,V1.0.0.125,V14.24,{'Skirmisher'},{'Top'},{'Top'},3,2,2,3,1,75,Physical,4800,880,{1: 'Runic Blade'},{1: 'Broken Wings'},{1: 'Ki Burst'},{1: 'Valor'},"{1: 'Blade of the Exile', 2: 'Wind Slash'}","{1: 'Runic Blade', 2: 'Broken Wings', 3: 'Ki B...",Konte Riven
152,Viego,234.0,Viego,The Ruined King,3,Fighter,Assassin,Unknown,"{'hp_base': 630, 'hp_lvl': 109, 'mp_base': 0, ...",Melee,2021-01-21,V11.2,V25.S1.1,{'Skirmisher'},{'Jungle'},{'Jungle'},3,1,2,2,1,20,Physical,4800,880,"{1: ""Sovereign's Domination""}",{1: 'Blade of the Ruined King'},{1: 'Spectral Maw'},{1: 'Harrowed Path'},{1: 'Heartbreaker'},"{1: ""Sovereign's Domination"", 2: 'Blade of the...",Unknown

In [ ]:
resource_map = {'Unknown': 'no resource'}
df['resource'] = df['resource'].map(resource_map).fillna(df['resource'])

In [ ]:
df.loc[df['resource'] == 'no resource']

,nickname,id,apiname,title,difficulty,herotype,alttype,resource,stats,rangetype,date,patch,changes,role,client_positions,external_positions,damage,toughness,control,mobility,utility,style,adaptivetype,be,rp,skill_i,skill_q,skill_w,skill_e,skill_r,skills,fullname
15,Bel'Veth,200.0,Belveth,the Empress of the Void,2,Fighter,NaN,no resource,"{'hp_base': 610, 'hp_lvl': 99, 'mp_base': 0, '...",Melee,2022-06-09,V12.11,V14.18,{'Skirmisher'},{'Jungle'},{'Jungle'},3,1,2,3,1,0,Physical,3150,790,{1: 'Death in Lavender'},{1: 'Void Surge'},{1: 'Above and Below'},{1: 'Royal Maelstrom'},{1: 'Endless Banquet'},"{1: 'Death in Lavender', 2: 'Void Surge', 3: '...",Unknown
38,Garen,86.0,Garen,The Might of Demacia,1,Fighter,Tank,no resource,"{'hp_base': 690, 'hp_lvl': 98, 'mp_base': 0, '...",Melee,2010-04-27,V1.0.0.83,V14.9,{'Juggernaut'},{'Top'},{'Top'},2,3,1,1,1,75,Physical,450,260,{1: 'Perseverance'},{1: 'Decisive Strike'},{1: 'Courage'},"{1: 'Judgment', 2: 'Judgment 2'}",{1: 'Demacian Justice'},"{1: 'Perseverance', 2: 'Decisive Strike', 3: '...",Garen Crownguard
62,Katarina,55.0,Katarina,the Sinister Blade,2,Assassin,Mage,no resource,"{'hp_base': 672, 'hp_lvl': 108, 'mp_base': 0, ...",Melee,2009-09-19,V0.9.25.21,V14.22,{'Assassin'},{'Middle'},{'Middle'},3,1,1,3,1,100,Magic,3150,790,"{1: 'Voracity', 2: 'Sinister Steel'}",{1: 'Bouncing Blade'},{1: 'Preparation'},{1: 'Shunpo'},{1: 'Death Lotus'},"{1: 'Voracity', 2: 'Sinister Steel', 3: 'Bounc...",Katarina Du Couteau
112,Riven,92.0,Riven,the Exile,2,Fighter,Assassin,no resource,"{'hp_base': 630, 'hp_lvl': 100, 'mp_base': 0, ...",Melee,2011-09-14,V1.0.0.125,V14.24,{'Skirmisher'},{'Top'},{'Top'},3,2,2,3,1,75,Physical,4800,880,{1: 'Runic Blade'},{1: 'Broken Wings'},{1: 'Ki Burst'},{1: 'Valor'},"{1: 'Blade of the Exile', 2: 'Wind Slash'}","{1: 'Runic Blade', 2: 'Broken Wings', 3: 'Ki B...",Konte Riven
152,Viego,234.0,Viego,The Ruined King,3,Fighter,Assassin,no resource,"{'hp_base': 630, 'hp_lvl': 109, 'mp_base': 0, ...",Melee,2021-01-21,V11.2,V25.S1.1,{'Skirmisher'},{'Jungle'},{'Jungle'},3,1,2,2,1,20,Physical,4800,880,"{1: ""Sovereign's Domination""}",{1: 'Blade of the Ruined King'},{1: 'Spectral Maw'},{1: 'Harrowed Path'},{1: 'Heartbreaker'},"{1: ""Sovereign's Domination"", 2: 'Blade of the...",Unknown

In [ ]:
df['alttype'].unique()

array(['Tank', 'Assassin', nan, 'Support', 'Marksman', 'Mage', 'Fighter'],
      dtype=object)

In [ ]:
df['alttype'] = df['alttype'].fillna('Unknown')
df.loc[df['alttype'] == 'Unknown']

,nickname,id,apiname,title,difficulty,herotype,alttype,resource,stats,rangetype,date,patch,changes,role,client_positions,external_positions,damage,toughness,control,mobility,utility,style,adaptivetype,be,rp,skill_i,skill_q,skill_w,skill_e,skill_r,skills,fullname
2,Akali,84.0,Akali,the Rogue Assassin,2,Assassin,Unknown,Energy,"{'hp_base': 600, 'hp_lvl': 119, 'mp_base': 200...",Melee,2010-05-11,V1.0.0.85,V14.18,{'Assassin'},"{'Middle', 'Top'}","{'Middle', 'Top'}",3,1,1,3,1,65,Physical,3150,790,"{1: ""Assassin's Mark""}",{1: 'Five Point Strike'},{1: 'Twilight Shroud'},{1: 'Shuriken Flip'},{1: 'Perfect Execution'},"{1: ""Assassin's Mark"", 2: 'Five Point Strike',...",Akali Jhomen Tethi
9,Aphelios,523.0,Aphelios,the Weapon of the Faithful,3,Marksman,Unknown,Mana,"{'hp_base': 600, 'hp_lvl': 102, 'mp_base': 348...",Ranged,2019-12-11,V9.24,V14.21,{'Marksman'},{'Bottom'},{'Bottom'},3,1,2,1,1,20,Physical,4800,880,"{1: 'The Hitman and the Seer', 2: 'Calibrum', ...","{1: 'Weapons of the Faithful', 2: 'Moonshot', ...",{1: 'Phase'},{1: 'Weapon Queue System'},{1: 'Moonlight Vigil'},"{1: 'The Hitman and the Seer', 2: 'Calibrum', ...",Unknown
11,Aurelion Sol,136.0,AurelionSol,The Star Forger,3,Mage,Unknown,Mana,"{'hp_base': 600, 'hp_lvl': 90, 'mp_base': 530,...",Ranged,2016-03-24,V6.6,V14.21,{'Battlemage'},{'Middle'},{'Middle'},3,1,2,2,1,100,Magic,4800,880,{1: 'Cosmic Creator'},{1: 'Breath of Light'},{1: 'Astral Flight'},{1: 'Singularity'},"{1: 'Falling Star', 2: 'The Skies Descend'}","{1: 'Cosmic Creator', 2: 'Breath of Light', 3:...",Unknown
15,Bel'Veth,200.0,Belveth,the Empress of the Void,2,Fighter,Unknown,no resource,"{'hp_base': 610, 'hp_lvl': 99, 'mp_base': 0, '...",Melee,2022-06-09,V12.11,V14.18,{'Skirmisher'},{'Jungle'},{'Jungle'},3,1,2,3,1,0,Physical,3150,790,{1: 'Death in Lavender'},{1: 'Void Surge'},{1: 'Above and Below'},{1: 'Royal Maelstrom'},{1: 'Endless Banquet'},"{1: 'Death in Lavender', 2: 'Void Surge', 3: '...",Unknown
20,Caitlyn,51.0,Caitlyn,the Sheriff of Piltover,1,Marksman,Unknown,Mana,"{'hp_base': 580, 'hp_lvl': 107, 'mp_base': 315...",Ranged,2011-01-04,V1.0.0.108,V14.24,{'Marksman'},{'Bottom'},{'Bottom'},3,1,2,2,1,10,Physical,450,260,{1: 'Headshot'},{1: 'Piltover Peacemaker'},{1: 'Yordle Snap Trap'},{1: '90 Caliber Net'},{1: 'Ace in the Hole'},"{1: 'Headshot', 2: 'Piltover Peacemaker', 3: '...",Unknown
22,Cassiopeia,69.0,Cassiopeia,the Serpent's Embrace,3,Mage,Unknown,Mana,"{'hp_base': 630, 'hp_lvl': 104, 'mp_base': 400...",Ranged,2010-12-14,v1.0.0.107,V25.S1.1,{'Battlemage'},{'Middle'},{'Middle'},3,1,3,1,1,100,Magic,4800,880,{1: 'Serpentine Grace'},{1: 'Noxious Blast'},{1: 'Miasma'},{1: 'Twin Fang'},{1: 'Petrifying Gaze'},"{1: 'Serpentine Grace', 2: 'Noxious Blast', 3:...",Cassiopeia Du Couteau
28,Draven,119.0,Draven,the Glorious Executioner,2,Marksman,Unknown,Mana,"{'hp_base': 675, 'hp_lvl': 104, 'mp_base': 361...",Ranged,2012-06-06,V1.0.0.140b,V14.11,{'Marksman'},{'Bottom'},{'Bottom'},3,1,1,2,1,10,Physical,4800,880,{1: 'League of Draven'},{1: 'Spinning Axe'},{1: 'Blood Rush'},{1: 'Stand Aside'},"{1: 'Whirling Death', 2: 'Whirling Death 2'}","{1: 'League of Draven', 2: 'Spinning Axe', 3: ...",Unknown
37,Gangplank,41.0,Gangplank,the Saltwater Scourge,3,Fighter,Unknown,Mana,"{'hp_base': 630, 'hp_lvl': 114, 'mp_base': 280...",Melee,2009-08-19,V0.9.22.15,V25.S1.1,{'Specialist'},{'Top'},{'Top'},3,1,1,1,2,75,Physical,3150,790,"{1: 'Trial by Fire', 2: 'Trial by Fire 2'}",{1: 'Parrrley'},{1: 'Remove Scurvy'},{1: 'Powder Keg'},{1: 'Cannon Barrage'},"{1: 'Trial by Fire', 2: 'Parrrley', 3: 'Remove...",Unknown
42,Graves,104.0,Graves,the Outlaw,2,Marksman,Unknown,Mana,"{'hp_base': 625, 'hp_lvl': 106, 'mp_base': 325...",Ranged,2011-10-19,V1.0.0.127,V14.24,{'Specialist'},{'Jungle'},{'Jungle'},3,2,1,2,2,20,Physical,4800,880,{1: 'New Destiny'},{1: 'End of the Line'},{1: 'Smoke Screen'},{1: 'Quickdraw'},{1: 'Collateral Damage'},"{1: 'New Destiny', 2: 'End of the Line', 3: 'S...",Malcolm Graves
55,Jinx,222.0,Jinx,the Loose Cannon,2,Marksman,Unknown,Mana,"{'hp_base': 630, 'hp_lvl': 105, 'mp_base': 260...",Ranged,2013-10-10,V3.12,V14.24,{'Marksman'},{'Bottom'},{'Bottom'},3,1,2,1,1,10,Physical,3150,790,{1: 'Get Excited!'},"{1: 'Switcheroo!', 2: 'Pow-Pow', 3: ""Rev'd up""}",{1: 'Zap!'},"{1: 'Flame Chompers!', 2: 'Flame Chompers! 2'}",{1: 'Super Mega Death Rocket!'},"{1: 'Get Excited!', 2: 'Switcheroo!', 3: 'Pow-...",Unknown
58,Kalista,429.0,Kalista,the Spear of Vengeance,3,Marksman,Unknown,Mana,"{'hp_base': 600, 'hp_lvl': 114, 'mp_base': 300...",Ranged,2014-11-20,V4.20,V25.S1.1,{'Marksman'},{'Bottom'},{'Bottom'},3,1,1,3,2,10,Physical,4800,880,{1: 'Martial Poise'},{1: 'Pierce'},{1: 'Sentinel'},{1: 'Rend'},"{1: ""Fate's Call""}","{1: 'Martial Poise', 2: 'Pierce', 3: 'Sentinel...",Unknown
60,Karthus,30.0,Karthus,the Deathsinger,2,Mage,Unknown,Mana,"{'hp_base': 620, 'hp_lvl': 110, 'mp_base': 467...",Ranged,2009-06-12,"June 12, 2009 Patch",V14.24,{'Battlemage'},{'Jungle'},{'Jungle'},3,1,1,1,2,100,Magic,3150,790,{1: 'Death Defied'},{1: 'Lay Waste'},{1: 'Wall of Pain'},{1: 'Defile'},{1: 'Requiem'},"{1: 'Death Defied', 2: 'Lay Waste', 3: 'Wall o...",Unknown
66,Kha'Zix,121.0,Khazix,the Voidreaver,2,Assassin,Unknown,Mana,"{'hp_base': 643, 'hp_lvl': 99, 'mp_base': 327,...",Melee,2012-09-27,V1.0.0.148,V14.23,{'Assassin'},{'Jungle'},{'Jungle'},3,1,1,2,1,55,Physical,4800,880,{1: 'Unseen Threat'},"{1: 'Taste Their Fear', 2: 'Evolved Reaper Cla...","{1: 'Void Spike', 2: 'Evolved Spike Racks'}","{1: 'Leap', 2: 'Evolved Wings'}","{1: 'Void Assault', 2: 'Evolved Adaptive Cloak...","{1: 'Unseen Threat', 2: 'Taste Their Fear', 3:...",Unknown
67,Kindred,203.0,Kindred,The Eternal Hunters,3,Marksman,Unknown,Mana,"{'hp_base': 595, 'hp_lvl': 104, 'mp_base': 300...",Ranged,2015-10-14,V5.20,V14.14,{'Marksman'},{'Jungle'},{'Jungle'},3,1,2,3,2,20,Physical,4800,880,{1: 'Mark of the Kindred'},{1: 'Dance of Arrows'},"{1: ""Wolf's Frenzy""}",{1: 'Mounting Dread'},"{1: ""Lamb's Respite""}","{1: 'Mark of the Kindred', 2: 'Dance of Arrows...",Lamb and Wolf
75,Lissandra,127.0,Lissandra,the Ice Witch,2,Mage,Unknown,Mana,"{'hp_base': 620, 'hp_lvl': 110, 'mp_base': 475...",Ranged,2013-04-30,V3.6,V14.18,{'Burst'},{'Middle'},{'Middle'},3,1,3,2,1,100,Magic,4800,880,{1: 'Iceborn Subjugation'},{1: 'Ice Shard'},{1: 'Ring of Frost'},{1: 'Glacial Path'},{1: 'Frozen Tomb'},"{1: 'Iceborn Subjugation', 2: 'Ice Shard', 3: ...",Unknown
105,Rakan,497.0,Rakan,The Charmer,2,Support,Unknown,Mana,"{'hp_base': 610, 'hp_lvl': 99, 'mp_base': 315,...",Melee,2017-04-19,V7.8,V14.20,{'Catcher'},{'Support'},{'Support'},1,2,3,3,3,90,Magic,4800,880,"{1: 'Fey Feathers', 2: ""Lover's Leap""}",{1: 'Gleaming Quill'},{1: 'Grand Entrance'},"{1: 'Battle Dance', 2: 'Battle Dance 2'}",{1: 'The Quickness'},"{1: 'Fey Feathers', 2: ""Lover's Leap"", 3: 'Gle...",Unknown
120,Shaco,35.0,Shaco,the Demon Jester,2,Assassin,Unknown,Mana,"{'hp_base': 630, 'hp_lvl': 99, 'mp_base': 297,...",Melee,2009-10-10,V0.9.25.34,V25.S1.1,{'Assassin'},{'Jungle'},"{'Jungle', 'Support'}",3,1,2,2,2,45,Physical,3150,790,{1: 'Backstab'},{1: 'Deceive'},{1: 'Jack in the Box'},{1: 'Two-Shiv Poison'},"{1: 'Hallucinate', 2: 'Command: Hallucinate'}","{1: 'Backstab', 2: 'Deceive', 3: 'Jack in the ...",Unknown
121,Shen,98.0,Shen,the Eye of Twilight,2,Tank,Unknown,Energy,"{'hp_base': 610, 'hp_lvl': 99, 'mp_base': 400,...",Melee,2010-03-24,V1.0.0.81,V14.22,{'Warden'},{'Top'},"{'Top', 'Support'}",2,3,2,2,3,45,Physical,3150,790,{1: 'Ki Barrier'},"{1: 'Twilight Assault', 2: 'Twilight Assault 2...","{1: ""Spirit's Refuge""}",{1: 'Shadow Dash'},"{1: 'Stand United', 2: 'Stand United 2'}","{1: 'Ki Barrier', 2: 'Twilight Assault', 3: ""S...",Unknown
125,Sivir,15.0,Sivir,the Battle Mistress,2,Marksman,Unknown,Mana,"{'hp_base': 600, 'hp_lvl': 104, 'mp_base': 340...",Ranged,2009-02-21,Alpha Week 2,V14.24,{'Marksman'},{'Bottom'},{'Bottom'},3,1,1,1,2,10,Physical,450,260,{1: 'Fleet of Foot'},{1: 'Boomerang Blade'},{1: 'Ricochet'},{1: 'Spell Shield'},{1: 'On the Hunt'},"{1: 'Fleet of Foot', 2: 'Boomerang Blade', 3: ...",Unknown
132,Syndra,134.0,Syndra,the Dark Sovereign,2,Mage,Unknown,Mana,"{'hp_base': 563, 'hp_lvl': 104, 'mp_base': 480...",Ranged,2012-09-13,V1.0.0.147,V14.24,{'Burst'},{'Middle'},{'Middle'},3,1,2,1,1,100,Magic,3150,790,{1: 'Transcendent'},{1: 'Dark Sphere'},"{1: 'Force of Will', 2: 'Force of Will 2'}",{1: 'Scatter the Weak'},{1: 'Unleashed Power'},"{1: 'Transcendent', 2: 'Dark Sphere', 3: 'Forc...",Unknown
135,Talon,91.0,Talon,the Blade's Shadow,2,Assassin,Unknown,Mana,"{'hp_base': 658, 'hp_lvl': 109, 'mp_base': 400...",Melee,2011-08-24,V1.0.0.124,V14.24,{'Assassin'},{'Middle'},{'Jungle'},3,1,1,2,1,65,Physical,3150,790,"{1: ""Blade's End""}",{1: 'Noxian Diplomacy'},{1: 'Rake'},"{1: ""Assassin's Path""}",{1: 'Shadow Assault'},"{1: ""Blade's End"", 2: 'Noxian Diplomacy', 3: '...",Talon Du Couteau
148,Veigar,45.0,Veigar,the Tiny Master of Evil,2,Mage,Unknown,Mana,"{'hp_base': 580, 'hp_lvl': 108, 'mp_base': 490...",Ranged,2009-07-24,V0.8.22.115,V14.24,{'Burst'},{'Middle'},"{'Middle', 'Support'}",3,1,3,1,1,100,Magic,1350,585,{1: 'Phenomenal Evil Power'},{1: 'Baleful Strike'},{1: 'Dark Matter'},{1: 'Event Horizon'},{1: 'Primordial Burst'},"{1: 'Phenomenal Evil Power', 2: 'Baleful Strik...",Unknown
150,Vex,711.0,Vex,the Gloomist,2,Mage,Unknown,Mana,"{'hp_base': 590, 'hp_lvl': 104, 'mp_base': 490...",Ranged,2021-09-23,V11.19,V14.9,{'Burst'},{'Middle'},{'Middle'},3,2,2,2,1,90,Magic,3150,790,"{1: ""Doom 'n Gloom""}",{1: 'Mistral Bolt'},{1: 'Personal Space'},{1: 'Looming Darkness'},{1: 'Shadow Surge'},"{1: ""Doom 'n Gloom"", 2: 'Mistral Bolt', 3: 'Pe...",Unknown
153,Viktor,112.0,Viktor,the Herald of the Arcane,3,Mage,Unknown,Mana,"{'hp_base': 600, 'hp_lvl': 100, 'mp_base': 405...",Ranged,2011-12-29,V1.0.0.131,V25.S1.1,{'Battlemage'},{'Middle'},{'Middle'},3,1,2,1,1,90,Magic,4800,880,"{1: 'Glorious Evolution', 2: 'Glorious Evoluti...","{1: 'Siphon Power', 2: 'Discharge'}",{1: 'Gravity Field'},{1: 'Hextech Ray'},"{1: 'Arcane Storm', 2: 'Arcane Storm 3'}","{1: 'Glorious Evolution', 2: 'Siphon Power', 3...",Unknown
158,Xayah,498.0,Xayah,the Rebel,2,Marksman,Unknown,Mana,"{'hp_base': 630, 'hp_lvl': 107, 'mp_base': 340...",Ranged,2017-04-19,V7.8,V14.21,{'Marksman'},{'Bottom'},{'Bottom'},3,2,3,1,1,30,Physical,4800,880,"{1: 'Clean Cuts', 2: ""Lover's Leap""}",{1: 'Double Daggers'},{1: 'Deadly Plumage'},{1: 'Bladecaller'},{1: 'Featherstorm'},"{1: 'Clean Cuts', 2: ""Lover's Leap"", 3: 'Doubl...",Unknown
166,Zed,238.0,Zed,the Master of Shadows,3,Assassin,Unknown,Energy,"{'hp_base': 654, 'hp_lvl': 99, 'mp_base': 200,...",Melee,2012-11-13,V1.0.0.151,V14.15,{'Assassin'},{'Middle'},"{'Middle', 'Jungle'}",3,1,1,3,1,55,Physical,1350,585,{1: 'Contempt for the Weak'},{1: 'Razor Shuriken'},"{1: 'Living Shadow', 2: 'Living Shadow 2'}",{1: 'Shadow Slash'},"{1: 'Death Mark', 2: 'Death Mark 2'}","{1: 'Contempt for the Weak', 2: 'Razor Shurike...",Unknown
167,Zeri,221.0,Zeri,The Spark of Zaun,2,Marksman,Unknown,Mana,"{'hp_base': 600, 'hp_lvl': 110, 'mp_base': 250...",Ranged,2022-01-20,V12.2,V14.18,{'Marksman'},{'Bottom'},{'Bottom'},2,1,2,3,0,35,Physical,4800,880,{1: 'Living Battery'},{1: 'Burst Fire'},{1: 'Ultrashock Laser'},{1: 'Spark Surge'},{1: 'Lightning Crash'},"{1: 'Living Battery', 2: 'Burst Fire', 3: 'Ult...",Unknown
168,Ziggs,115.0,Ziggs,the Hexplosives Expert,2,Mage,Unknown,Mana,"{'hp_base': 606, 'hp_lvl': 106, 'mp_base': 480...",Ranged,2012-02-01,V1.0.0.133,V14.18,{'Artillery'},{'Bottom'},"{'Middle', 'Bottom'}",3,1,2,2,1,90,Magic,4800,880,{1: 'Short Fuse'},{1: 'Bouncing Bomb'},{1: 'Satchel Charge'},{1: 'Hexplosive Minefield'},{1: 'Mega Inferno Bomb'},"{1: 'Short Fuse', 2: 'Bouncing Bomb', 3: 'Satc...",Unknown

In [ ]:
df.loc[df['nickname'] == 'Akali', 'alttype'] = 'Assassin'

In [ ]:
df.loc[df['nickname'] == 'Aphelios', 'alttype'] = 'Marksman'
df.loc[df['nickname'] == 'Caitlyn', 'alttype'] = 'Marksman'
df.loc[df['nickname'] == 'Kalista', 'alttype'] = 'Marksman'
df.loc[df['nickname'] == 'Jinx', 'alttype'] = 'Marksman'
df.loc[df['nickname'] == 'Shaco', 'alttype'] = 'Assassin'
df.loc[df['nickname'] == 'Talon', 'alttype'] = 'Assassin'
df.loc[df['nickname'] == 'Veigar', 'alttype'] = 'Burst'

In [ ]:
df.loc[df['nickname'] == 'Ziggs', 'alttype'] = 'Artillery'
df.loc[df['nickname'] == 'Zeri', 'alttype'] = 'Marksman'
df.loc[df['nickname'] == 'Rakan', 'alttype'] = 'Catcher'
df.loc[df['nickname'] == 'Lissandra', 'alttype'] = 'Burst'
df.loc[df['nickname'] == 'Karthus', 'alttype'] = 'Battlemage'
df.loc[df['apiname'] == 'Belveth', 'alttype'] = 'Skirmisher'
df.loc[df['nickname'] == 'Gangplank', 'alttype'] = 'Specialist'

In [ ]:
df.loc[df['apiname'] == 'AurelionSol', 'alttype'] = 'Battlemage'
df.loc[df['nickname'] == 'Xayah', 'alttype'] = 'Marksman'
df.loc[df['nickname'] == 'Shen', 'alttype'] = 'Warden'
df.loc[df['nickname'] == 'Sivir', 'alttype'] = 'Marksman'

In [ ]:
df.loc[df['nickname'] == 'Zed', 'alttype'] = 'Assassin'
df.loc[df['nickname'] == 'Syndra', 'alttype'] = 'Burst'
df.loc[df['nickname'] == 'Viktor', 'alttype'] = 'Battlemage'
df.loc[df['apiname'] == 'Khazix', 'alttype'] = 'Assassin'

In [ ]:
df.loc[df['alttype'] == 'Unknown']

,nickname,id,apiname,title,difficulty,herotype,alttype,resource,stats,rangetype,date,patch,changes,role,client_positions,external_positions,damage,toughness,control,mobility,utility,style,adaptivetype,be,rp,skill_i,skill_q,skill_w,skill_e,skill_r,skills,fullname
22,Cassiopeia,69.0,Cassiopeia,the Serpent's Embrace,3,Mage,Unknown,Mana,"{'hp_base': 630, 'hp_lvl': 104, 'mp_base': 400...",Ranged,2010-12-14,v1.0.0.107,V25.S1.1,{'Battlemage'},{'Middle'},{'Middle'},3,1,3,1,1,100,Magic,4800,880,{1: 'Serpentine Grace'},{1: 'Noxious Blast'},{1: 'Miasma'},{1: 'Twin Fang'},{1: 'Petrifying Gaze'},"{1: 'Serpentine Grace', 2: 'Noxious Blast', 3:...",Cassiopeia Du Couteau
28,Draven,119.0,Draven,the Glorious Executioner,2,Marksman,Unknown,Mana,"{'hp_base': 675, 'hp_lvl': 104, 'mp_base': 361...",Ranged,2012-06-06,V1.0.0.140b,V14.11,{'Marksman'},{'Bottom'},{'Bottom'},3,1,1,2,1,10,Physical,4800,880,{1: 'League of Draven'},{1: 'Spinning Axe'},{1: 'Blood Rush'},{1: 'Stand Aside'},"{1: 'Whirling Death', 2: 'Whirling Death 2'}","{1: 'League of Draven', 2: 'Spinning Axe', 3: ...",Unknown
42,Graves,104.0,Graves,the Outlaw,2,Marksman,Unknown,Mana,"{'hp_base': 625, 'hp_lvl': 106, 'mp_base': 325...",Ranged,2011-10-19,V1.0.0.127,V14.24,{'Specialist'},{'Jungle'},{'Jungle'},3,2,1,2,2,20,Physical,4800,880,{1: 'New Destiny'},{1: 'End of the Line'},{1: 'Smoke Screen'},{1: 'Quickdraw'},{1: 'Collateral Damage'},"{1: 'New Destiny', 2: 'End of the Line', 3: 'S...",Malcolm Graves
67,Kindred,203.0,Kindred,The Eternal Hunters,3,Marksman,Unknown,Mana,"{'hp_base': 595, 'hp_lvl': 104, 'mp_base': 300...",Ranged,2015-10-14,V5.20,V14.14,{'Marksman'},{'Jungle'},{'Jungle'},3,1,2,3,2,20,Physical,4800,880,{1: 'Mark of the Kindred'},{1: 'Dance of Arrows'},"{1: ""Wolf's Frenzy""}",{1: 'Mounting Dread'},"{1: ""Lamb's Respite""}","{1: 'Mark of the Kindred', 2: 'Dance of Arrows...",Lamb and Wolf
150,Vex,711.0,Vex,the Gloomist,2,Mage,Unknown,Mana,"{'hp_base': 590, 'hp_lvl': 104, 'mp_base': 490...",Ranged,2021-09-23,V11.19,V14.9,{'Burst'},{'Middle'},{'Middle'},3,2,2,2,1,90,Magic,3150,790,"{1: ""Doom 'n Gloom""}",{1: 'Mistral Bolt'},{1: 'Personal Space'},{1: 'Looming Darkness'},{1: 'Shadow Surge'},"{1: ""Doom 'n Gloom"", 2: 'Mistral Bolt', 3: 'Pe...",Unknown

In [ ]:
df.columns

Index(['nickname', 'id', 'apiname', 'title', 'difficulty', 'herotype',
       'alttype', 'resource', 'stats', 'rangetype', 'date', 'patch', 'changes',
       'role', 'client_positions', 'external_positions', 'damage', 'toughness',
       'control', 'mobility', 'utility', 'style', 'adaptivetype', 'be', 'rp',
       'skill_i', 'skill_q', 'skill_w', 'skill_e', 'skill_r', 'skills',
       'fullname'],
      dtype='object')

**¿Cual es el personaje Tanque mas dificil de jugar?**

In [ ]:
df['herotype'].unique()

array(['Fighter', 'Mage', 'Assassin', 'Marksman', 'Tank', 'Support'],
      dtype=object)

In [ ]:
df['difficulty'].unique()

array([2, 3, 1], dtype=int8)

In [ ]:
mask = (df['herotype'] == 'Tank') & (df['difficulty'] == 3)
df.loc[mask][['nickname', 'apiname', 'title', 'difficulty', 'herotype', 'alttype', 'resource', 'rangetype', 'role']]

,nickname,apiname,title,difficulty,herotype,alttype,resource,rangetype,role
56,K'Sante,KSante,the Pride of Nazumah,3,Tank,Fighter,Mana,Melee,"{'Warden', 'Skirmisher'}"

**Listar los heroes con la mayor dificultad dentro de la clase (alttype) Support.**

In [ ]:
df['alttype'].unique()

array(['Tank', 'Assassin', 'Support', 'Marksman', 'Battlemage', 'Mage',
       'Skirmisher', 'Unknown', 'Fighter', 'Specialist', 'Burst',
       'Catcher', 'Warden', 'Artillery'], dtype=object)

In [ ]:
df['alttype'].value_counts()

alttype
Mage          38
Assassin      36
Support       28
Tank          25
Fighter       17
Marksman      12
Unknown        5
Battlemage     3
Burst          3
Skirmisher     1
Specialist     1
Catcher        1
Warden         1
Artillery      1
Name: count, dtype: int64

In [ ]:
alttype_grp = df.groupby('alttype')
support = alttype_grp.get_group('Support')
mask_supp = (df['difficulty'] == 3)
support.loc[mask_supp]

,nickname,id,apiname,title,difficulty,herotype,alttype,resource,stats,rangetype,date,patch,changes,role,client_positions,external_positions,damage,toughness,control,mobility,utility,style,adaptivetype,be,rp,skill_i,skill_q,skill_w,skill_e,skill_r,skills,fullname
7,Anivia,34.0,Anivia,the Cryophoenix,3,Mage,Support,Mana,"{'hp_base': 550, 'hp_lvl': 92, 'mp_base': 495,...",Ranged,2009-07-10,"July 10, 2009 Patch",V14.22,{'Battlemage'},{'Middle'},{'Middle'},3,1,3,1,2,100,Magic,3150,790,{1: 'Rebirth'},{1: 'Flash Frost'},{1: 'Crystallize'},{1: 'Frostbite'},{1: 'Glacial Storm'},"{1: 'Rebirth', 2: 'Flash Frost', 3: 'Crystalli...",Unknown
46,Hwei,910.0,Hwei,the Visionary,3,Mage,Support,Mana,"{'hp_base': 580, 'hp_lvl': 109, 'mp_base': 480...",Ranged,2023-12-05,V13.24,V14.22,{'Artillery'},"{'Middle', 'Support'}","{'Middle', 'Support'}",3,1,3,1,2,90,Magic,6300,975,{1: 'Signature of the Visionary'},"{1: 'Subject: Disaster', 2: 'Devastating Fire'...","{1: 'Subject: Serenity', 2: 'Fleeting Current'...","{1: 'Subject: Torment', 2: 'Grim Visage', 3: '...","{1: 'Spiraling Despair', 2: 'Wash Brush'}","{1: 'Signature of the Visionary', 2: 'Subject:...",Unknown
170,Zoe,142.0,Zoe,the Aspect of Twilight,3,Mage,Support,Mana,"{'hp_base': 630, 'hp_lvl': 106, 'mp_base': 425...",Ranged,2017-11-21,V7.23,V25.S1.1,{'Burst'},{'Middle'},{'Middle'},3,1,2,2,1,100,Magic,4800,880,{1: 'More Sparkles!'},"{1: 'Paddle Star', 2: 'Paddle Star 2'}",{1: 'Spell Thief'},{1: 'Sleepy Trouble Bubble'},{1: 'Portal Jump'},"{1: 'More Sparkles!', 2: 'Paddle Star', 3: 'Sp...",Unknown

**Agrupar la cantidad de heroes por tipo (herotype) y por clase (alttype)**

In [ ]:
df.groupby(['herotype', 'alttype'])['id'].count()

herotype  alttype
Assassin  Assassin       5
          Fighter        5
          Mage           7
Fighter   Assassin      19
          Mage           5
          Skirmisher     1
          Specialist     1
          Tank          23
Mage      Artillery      1
          Assassin       4
          Battlemage     3
          Burst          3
          Fighter        2
          Marksman       4
          Support       18
          Unknown        2
Marksman  Assassin       7
          Fighter        1
          Mage           9
          Marksman       7
          Support        1
          Unknown        3
Support   Assassin       1
          Catcher        1
          Mage          12
          Marksman       1
          Tank           2
Tank      Fighter        9
          Mage           5
          Support        9
          Warden         1
Name: id, dtype: int64