<a href="https://colab.research.google.com/github/mfernandezzz/Pruebas_Tecnicas/blob/main/TT_Tinder.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df = pd.read_csv('/content/encuestas_tinder.csv')
pd.set_option('display.max_columns', None)

In [ ]:
df.shape

(453, 8)

In [ ]:
df.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 453 entries, 0 to 452
Data columns (total 8 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   ID                        453 non-null    int64
 1   Segment Type              453 non-null    object
 2   Segment Description       453 non-null    object
 3   Answer                    453 non-null    object
 4   Count                     453 non-null    int64
 5   Percentage                453 non-null    float64
 6   It became a Relationship  453 non-null    object
 7   Gender                    453 non-null    object
dtypes: float64(1), int64(2), object(5)
memory usage: 140.3 KB

In [ ]:
#for c in df.select_dtypes('object'):
#  df[c] = df[c].astype('object')

In [ ]:
for i in df.select_dtypes('integer'):
  df[i] = pd.to_numeric(df[i], downcast='integer')

In [ ]:
for f in df.select_dtypes('float'):
  df[f] = pd.to_numeric(df[f], downcast='float')

In [ ]:
df.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 453 entries, 0 to 452
Data columns (total 8 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   ID                        453 non-null    int32
 1   Segment Type              453 non-null    object
 2   Segment Description       453 non-null    object
 3   Answer                    453 non-null    object
 4   Count                     453 non-null    int16
 5   Percentage                453 non-null    float32
 6   It became a Relationship  453 non-null    object
 7   Gender                    453 non-null    object
dtypes: float32(1), int16(1), int32(1), object(5)
memory usage: 134.1 KB

In [ ]:
df.columns = (
    df.columns
    .str.lower()
    .str.strip()
    .str.replace(' ', '_')
)
df.columns

Index(['id', 'segment_type', 'segment_description', 'answer', 'count',
       'percentage', 'it_became_a_relationship', 'gender'],
      dtype='object')

In [ ]:
nulls_count = df.isnull().sum()
nulls_count[nulls_count > 0].sort_values(ascending=False)

Series([], dtype: int64)

In [ ]:
nulls_percentage = df.isnull().mean()*100
nulls_percentage[nulls_percentage > 0].sort_values(ascending=False)

Series([], dtype: float64)

In [ ]:
duplicates_sum = df.duplicated().sum()
duplicates_sum

np.int64(0)

In [ ]:
duplicates_percentage = (df.duplicated().sum()/df.shape[0]) * 100
duplicates_percentage

np.float64(0.0)

In [ ]:
show_duplicates = df[df.duplicated(keep=False)].sort_values(by=list(df.columns)).head()
show_duplicates

Empty DataFrame
Columns: [id, segment_type, segment_description, answer, count, percentage, it_became_a_relationship, gender]
Index: []

In [ ]:
# df = df.drop_duplicates()

**¿Que sexo consigue mas citas?**

In [ ]:
df.columns

Index(['id', 'segment_type', 'segment_description', 'answer', 'count',
       'percentage', 'it_became_a_relationship', 'gender'],
      dtype='object')

In [ ]:
df.head()

,id,segment_type,segment_description,answer,count,percentage,it_became_a_relationship,gender
0,292881,Mobile,Mobile respondents,Yes,797,0.207,Yes,male
1,292883,Mobile,Mobile respondents,No,1969,0.511,No,female
2,292885,Mobile,Mobile respondents,I don't use Tinder,1090,0.283,Yes,male
3,292887,Web,Web-based respondents,Yes,0,0.000,No,female
4,292889,Web,Web-based respondents,No,0,0.000,No,female

In [ ]:
df['gender'].unique()

array(['male', 'female'], dtype=object)

In [ ]:
df['answer'].value_counts()

answer
Yes                   151
No                    151
I don't use Tinder    151
Name: count, dtype: int64

In [ ]:
mask = df['answer'] == 'Yes'
tinder_date = df.loc[mask]
tinder_date.shape

(151, 8)

In [ ]:
tinder_date.head()

,id,segment_type,segment_description,answer,count,percentage,it_became_a_relationship,gender
0,292881,Mobile,Mobile respondents,Yes,797,0.207,Yes,male
3,292887,Web,Web-based respondents,Yes,0,0.000,No,female
6,292893,Gender,Male respondents,Yes,472,0.213,Yes,male
9,292899,Gender,Female respondents,Yes,325,0.198,No,female
12,292905,University,Chapman University,Yes,13,0.206,No,female

In [ ]:
tinder_date['gender'].value_counts()

gender
female    102
male       49
Name: count, dtype: int64

In [ ]:
tinder_date['gender'].value_counts(normalize=True)

gender
female    0.675497
male      0.324503
Name: proportion, dtype: float64

In [ ]:
date_by_sex = pd.DataFrame(tinder_date['gender'].value_counts()).reset_index()
date_by_sex.rename(columns={'gender': 'sex', 'count': 'dates'}, inplace=True)
date_by_sex['%'] = round((date_by_sex['dates'] / date_by_sex['dates'].sum()) * 100, 2)

In [ ]:
date_by_sex

      sex  dates      %
0  female    102  67.55
1    male     49  32.45

**¿Que sexo consigue mas parejas?**

In [ ]:
mask = (df['answer'] == 'Yes') & (df['it_became_a_relationship'] == 'Yes')
relationship = df.loc[mask]
relationship.shape

(44, 8)

In [ ]:
relationship.head()

,id,segment_type,segment_description,answer,count,percentage,it_became_a_relationship,gender
0,292881,Mobile,Mobile respondents,Yes,797,0.207,Yes,male
6,292893,Gender,Male respondents,Yes,472,0.213,Yes,male
24,292929,University,Georgetown University,Yes,2,0.500,Yes,male
30,292941,University,Indiana University,Yes,9,0.205,Yes,male
42,292965,University,Princeton University,Yes,1,0.500,Yes,male

In [ ]:
relationship['gender'].value_counts(normalize=True)

gender
female    0.636364
male      0.363636
Name: proportion, dtype: float64

In [ ]:
relationship_by_sex = pd.DataFrame(relationship['gender'].value_counts()).reset_index()
relationship_by_sex.rename(columns={'gender': 'sex', 'count': 'total_relationships'}, inplace=True)
relationship_by_sex['%'] = round((relationship_by_sex['total_relationships'] / relationship_by_sex['total_relationships'].sum()) * 100, 2)
relationship_by_sex

      sex  total_relationships      %
0  female                   28  63.64
1    male                   16  36.36

**Entre quienes respondieron haber tenido una cita, ¿Cual es el porcentaje de personas que consiguieron pareja?**

In [ ]:
tinder_date.head()

,id,segment_type,segment_description,answer,count,percentage,it_became_a_relationship,gender
0,292881,Mobile,Mobile respondents,Yes,797,0.207,Yes,male
3,292887,Web,Web-based respondents,Yes,0,0.000,No,female
6,292893,Gender,Male respondents,Yes,472,0.213,Yes,male
9,292899,Gender,Female respondents,Yes,325,0.198,No,female
12,292905,University,Chapman University,Yes,13,0.206,No,female

In [ ]:
relationship_true = pd.DataFrame(tinder_date['it_became_a_relationship'].value_counts()).reset_index()
relationship_true['%'] = round(relationship_true['count']  / relationship_true['count'].sum() * 100, 2)
relationship_true

  it_became_a_relationship  count      %
0                       No    107  70.86
1                      Yes     44  29.14

In [ ]:
df['segment_type'].value_counts()

segment_type
University    441
Gender          6
Web             3
Mobile          3
Name: count, dtype: int64

In [ ]:
df['segment_type'].unique()

array(['Mobile', 'Web', 'Gender', 'University'], dtype=object)

In [ ]:
segment_grp = df.groupby('segment_type')

In [ ]:
segment_university = segment_grp.get_group('University')
segment_university.shape

(441, 8)